import { DAY_MINUTES, isSchedule, scheduleAt } from "./schedule";
import type { EscapeObjective, EscapeObjectiveId, GameSnapshot, ItemId, SimulationContext } from "./model";
const BASE_OBJECTIVES:readonly EscapeObjective[]=[
{id:"attend-roll-call",label:"Отметиться на утренней перекличке",completed:false},
{id:"find-metal-strip",label:"Найти тонкую металлическую пластину",completed:false},
{id:"find-cloth-tape",label:"Добыть тканевую ленту в мастерской",completed:false},
{id:"craft-service-shim",label:"Собрать самодельный сервисный ключ",completed:false},
{id:"reach-maintenance",label:"Проникнуть в служебную зону",completed:false},
];
export function createInitialSnapshot():GameSnapshot{return{version:1,day:1,minuteOfDay:444,stats:{health:100,stamina:100,suspicion:5,reputation:0,money:12,strength:1,intelligence:1},inventory:[],objectives:BASE_OBJECTIVES.map(o=>({...o})),flags:{lockerSearched:false,workshopBinSearched:false,serviceHatchUnlocked:false,firstRouteComplete:false,rollCallAttendedToday:false},capturedCount:0};}
export function hasItem(s:GameSnapshot,itemId:ItemId,q=1){return(s.inventory.find(x=>x.itemId===itemId)?.quantity??0)>=q;}
export function addItem(s:GameSnapshot,itemId:ItemId,q=1):GameSnapshot{const inventory=s.inventory.map(x=>({...x}));const slot=inventory.find(x=>x.itemId===itemId);if(slot)slot.quantity+=q;else inventory.push({itemId,quantity:q});return{...s,inventory};}
export function removeItem(s:GameSnapshot,itemId:ItemId,q=1):GameSnapshot{return{...s,inventory:s.inventory.map(x=>x.itemId===itemId?{...x,quantity:x.quantity-q}:{...x}).filter(x=>x.quantity>0)};}
export function completeObjective(s:GameSnapshot,id:EscapeObjectiveId):GameSnapshot{return{...s,objectives:s.objectives.map(o=>o.id===id?{...o,completed:true}:{...o})};}
export function searchLocker(s:GameSnapshot){if(s.flags.lockerSearched)return{snapshot:s,message:"Шкафчик уже пуст."};let n=completeObjective(addItem(s,"metal-strip"),"find-metal-strip");n={...n,flags:{...n.flags,lockerSearched:true}};return{snapshot:n,message:"Найдена тонкая металлическая пластина."};}
export function searchWorkshopBin(s:GameSnapshot){if(s.flags.workshopBinSearched)return{snapshot:s,message:"В ящике больше ничего полезного."};let n=completeObjective(addItem(s,"cloth-tape"),"find-cloth-tape");n={...n,flags:{...n.flags,workshopBinSearched:true}};return{snapshot:n,message:"Найдена тканевая лента."};}
export function craftServiceShim(s:GameSnapshot){if(hasItem(s,"service-shim"))return{snapshot:s,message:"Сервисный ключ уже собран.",ok:false};if(!hasItem(s,"metal-strip")||!hasItem(s,"cloth-tape"))return{snapshot:s,message:"Нужны металлическая пластина и тканевая лента.",ok:false};let n=removeItem(removeItem(s,"metal-strip"),"cloth-tape");n=completeObjective(addItem(n,"service-shim"),"craft-service-shim");n={...n,stats:{...n.stats,intelligence:n.stats.intelligence+1}};return{snapshot:n,message:"Собран самодельный сервисный ключ.",ok:true};}
export function unlockServiceHatch(s:GameSnapshot){if(s.flags.serviceHatchUnlocked)return{snapshot:s,message:"Служебный люк уже открыт.",ok:true};if(!hasItem(s,"service-shim"))return{snapshot:s,message:"Замок не поддаётся. Нужен подходящий инструмент.",ok:false};const n={...s,flags:{...s.flags,serviceHatchUnlocked:true},stats:{...s.stats,suspicion:Math.min(100,s.stats.suspicion+8)}};return{snapshot:n,message:"Замок поддался. Служебный проход открыт.",ok:true};}
export function reachMaintenance(s:GameSnapshot):GameSnapshot{if(s.flags.firstRouteComplete)return s;let n=completeObjective(s,"reach-maintenance");return{...n,flags:{...n.flags,firstRouteComplete:true},stats:{...n.stats,reputation:n.stats.reputation+10,money:n.stats.money+25}};}
export function tickSimulation(s:GameSnapshot,elapsed:number,ctx:SimulationContext):GameSnapshot{if(elapsed<=0)return s;let minuteOfDay=s.minuteOfDay+elapsed,day=s.day,flags={...s.flags};while(minuteOfDay>=DAY_MINUTES){minuteOfDay-=DAY_MINUTES;day++;flags.rollCallAttendedToday=false;}const active=scheduleAt(minuteOfDay),required=active.requiredZone,compliant=!required||ctx.playerZone===required;let suspicion=s.stats.suspicion;if(!compliant)suspicion+=elapsed*(ctx.guardCanSeePlayer?4.5:1.2);else suspicion-=elapsed*1.5;if(ctx.guardCanSeePlayer&&ctx.playerZone==="maintenance")suspicion+=elapsed*7;let n:GameSnapshot={...s,day,minuteOfDay,flags,stats:{...s.stats,suspicion:Math.max(0,Math.min(100,suspicion)),stamina:Math.max(20,Math.min(100,s.stats.stamina+elapsed*.8))}};if(isSchedule("roll-call",minuteOfDay)&&ctx.playerZone==="roll-call"&&!n.flags.rollCallAttendedToday){n=completeObjective(n,"attend-roll-call");n={...n,flags:{...n.flags,rollCallAttendedToday:true}};}return n;}
export function capturePlayer(s:GameSnapshot):GameSnapshot{return{...s,capturedCount:s.capturedCount+1,stats:{...s.stats,health:100,stamina:100,suspicion:18,money:Math.max(0,s.stats.money-3)}};}
