name = "blackcrown-game"
compatibility_date = "2026-07-02"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "LEADERBOARD_DB"
database_name = "evofish-leaderboard-db"
database_id = "272720c6-0967-42fb-bbc4-95257cc02abd"
