export const EVOFISH_MOBILE_CSS = `
html,body{width:100%!important;height:100%!important;overflow:hidden!important;overscroll-behavior:none!important;background:#031827!important;touch-action:none!important;-webkit-user-select:none!important;user-select:none!important}canvas{width:100vw!important;height:100dvh!important;touch-action:none!important}
#hud{left:max(10px,env(safe-area-inset-left))!important;top:max(10px,env(safe-area-inset-top))!important;width:106px!important;min-width:0!important;padding:8px 9px!important;border-radius:16px!important;transform:none!important;background:rgba(2,18,30,.34)!important;border:1px solid rgba(150,230,255,.10)!important;box-shadow:0 12px 34px rgba(0,0,0,.14)!important;backdrop-filter:blur(10px)!important;-webkit-backdrop-filter:blur(10px)!important;pointer-events:none!important}
#hud>.row{min-height:18px!important;gap:8px!important;align-items:center!important;font-size:11px!important;line-height:1!important}#hud>.row:nth-child(1),#hud>.row:nth-child(2),#hud>.row:nth-child(3),#hud>.row:nth-child(8),#hud>.row:nth-child(9),#hud>.row:nth-child(10){display:none!important}
#hud>.row:nth-child(4),#hud>.row:nth-child(5),#hud>.row:nth-child(6),#hud>.row:nth-child(7){display:flex!important;justify-content:space-between!important}#hud>.row span:first-child{font-size:0!important}#hud>.row:nth-child(4) span:first-child:after{content:'Lv';font-size:11px;font-weight:900}#hud>.row:nth-child(5) span:first-child:after{content:'Mass';font-size:11px;font-weight:900}#hud>.row:nth-child(6) span:first-child:after{content:'DMG';font-size:11px;font-weight:900}#hud>.row:nth-child(7) span:first-child:after{content:'SPD';font-size:11px;font-weight:900}#hud>.row span:last-child{font-size:12px!important;font-weight:900!important;color:rgba(231,242,255,.94)!important}
#bars{margin-top:6px!important}#bars .row{display:none!important}.bar{height:5px!important;margin:4px 0!important;background:rgba(255,255,255,.08)!important;border-radius:999px!important}
#tips{display:none!important}#dock{display:none!important}
#shade{background:rgba(0,0,0,.46)!important;backdrop-filter:blur(6px)!important;-webkit-backdrop-filter:blur(6px)!important;z-index:118!important}
#drawer{left:max(10px,env(safe-area-inset-left))!important;right:max(10px,env(safe-area-inset-right))!important;bottom:max(10px,env(safe-area-inset-bottom))!important;width:auto!important;max-height:68dvh!important;border-radius:24px!important;background:rgba(2,16,27,.96)!important;border:1px solid rgba(150,230,255,.14)!important;box-shadow:0 -16px 48px rgba(0,0,0,.36)!important;z-index:125!important;overflow:hidden!important}#drawerHeader{padding:12px 14px!important}#drawerTitle{font-size:14px!important;font-weight:900!important}#drawerClose{border-radius:14px!important;background:rgba(255,255,255,.07)!important}#drawerBody{max-height:calc(68dvh - 54px)!important;overflow:auto!important;-webkit-overflow-scrolling:touch!important;padding:12px!important}.card{border-radius:16px!important}.row2{gap:10px!important}.btn{min-height:38px!important;border-radius:14px!important}
#pickOverlay{padding:12px!important;z-index:140!important;background:rgba(0,0,0,.58)!important;backdrop-filter:blur(8px)!important;-webkit-backdrop-filter:blur(8px)!important}#pickPanel{width:100%!important;max-width:720px!important;max-height:78dvh!important;overflow:auto!important;border-radius:24px!important;background:rgba(2,16,27,.96)!important;padding:14px!important}#choices{grid-template-columns:1fr!important;gap:10px!important}.pickCard{border-radius:16px!important;padding:12px!important}
#toast{top:max(10px,env(safe-area-inset-top))!important;right:max(10px,env(safe-area-inset-right))!important;max-width:250px!important;border-radius:16px!important;z-index:150!important;background:rgba(2,16,27,.88)!important}
#start{background:radial-gradient(circle at 50% 35%,#0b4764,#031827 72%)!important}#start .box{width:min(420px,90vw)!important;padding:18px!important;border-radius:24px!important;background:rgba(2,16,27,.72)!important;border:1px solid rgba(150,230,255,.14)!important;box-shadow:0 22px 70px rgba(0,0,0,.35)!important}#start h1{font-size:22px!important}#btnStart{width:100%!important;justify-content:center!important;min-height:48px!important;border-radius:18px!important;background:linear-gradient(180deg,rgba(90,240,220,.28),rgba(50,170,255,.18))!important;border:1px solid rgba(120,240,255,.26)!important}
@media (orientation:landscape){#hud{width:98px!important;padding:6px 8px!important;border-radius:15px!important}#hud>.row{min-height:16px!important}#hud>.row span:last-child{font-size:11px!important}.bar{height:4px!important;margin:3px 0!important}#drawer{left:auto!important;width:min(430px,42vw)!important;right:max(10px,env(safe-area-inset-right))!important;max-height:82dvh!important}#drawerBody{max-height:calc(82dvh - 54px)!important}#choices{grid-template-columns:repeat(3,minmax(0,1fr))!important}}
`;
