export const EVOFISH_MOBILE_CSS = `
html,body{width:100%!important;height:100%!important;overflow:hidden!important;overscroll-behavior:none!important;background:#031827!important;touch-action:none!important;-webkit-user-select:none!important;user-select:none!important;-webkit-tap-highlight-color:transparent!important}canvas{width:100vw!important;height:100dvh!important;touch-action:none!important;background:#031827!important}
#hud{left:max(10px,env(safe-area-inset-left))!important;top:max(10px,env(safe-area-inset-top))!important;width:108px!important;min-width:0!important;padding:8px 9px!important;border-radius:17px!important;transform:none!important;background:linear-gradient(180deg,rgba(2,18,30,.46),rgba(2,18,30,.27))!important;border:1px solid rgba(150,230,255,.12)!important;box-shadow:0 14px 38px rgba(0,0,0,.18)!important;backdrop-filter:blur(10px) saturate(1.18)!important;-webkit-backdrop-filter:blur(10px) saturate(1.18)!important;pointer-events:none!important}
#hud>.row{min-height:18px!important;gap:8px!important;align-items:center!important;font-size:11px!important;line-height:1!important}#hud>.row:nth-child(1),#hud>.row:nth-child(2),#hud>.row:nth-child(3),#hud>.row:nth-child(8),#hud>.row:nth-child(9),#hud>.row:nth-child(10){display:none!important}
#hud>.row:nth-child(4),#hud>.row:nth-child(5),#hud>.row:nth-child(6),#hud>.row:nth-child(7){display:flex!important;justify-content:space-between!important}#hud>.row span:first-child{font-size:0!important}#hud>.row:nth-child(4) span:first-child:after{content:'LV';font-size:10px;font-weight:950;opacity:.82}#hud>.row:nth-child(5) span:first-child:after{content:'MASS';font-size:10px;font-weight:950;opacity:.82}#hud>.row:nth-child(6) span:first-child:after{content:'DMG';font-size:10px;font-weight:950;opacity:.82}#hud>.row:nth-child(7) span:first-child:after{content:'SPD';font-size:10px;font-weight:950;opacity:.82}#hud>.row span:last-child{font-size:12px!important;font-weight:950!important;color:rgba(231,242,255,.96)!important}
#bars{margin-top:6px!important}#bars .row{display:none!important}.bar{height:5px!important;margin:4px 0!important;background:rgba(255,255,255,.075)!important;border-radius:999px!important;box-shadow:inset 0 0 0 1px rgba(255,255,255,.035)!important}.bar>i{box-shadow:0 0 12px rgba(120,240,255,.18)!important}
#tips{display:none!important}#dock{display:none!important}
#shade{background:rgba(0,0,0,.48)!important;backdrop-filter:blur(7px)!important;-webkit-backdrop-filter:blur(7px)!important;z-index:118!important}
#drawer{left:max(10px,env(safe-area-inset-left))!important;right:max(10px,env(safe-area-inset-right))!important;bottom:max(10px,env(safe-area-inset-bottom))!important;width:auto!important;max-height:70dvh!important;border-radius:24px!important;background:linear-gradient(180deg,rgba(4,22,36,.98),rgba(2,12,22,.98))!important;border:1px solid rgba(150,230,255,.16)!important;box-shadow:0 -18px 56px rgba(0,0,0,.40)!important;z-index:125!important;overflow:hidden!important}#drawerHeader{padding:12px 14px!important}#drawerTitle{font-size:14px!important;font-weight:950!important}#drawerClose{border-radius:14px!important;background:rgba(255,255,255,.075)!important}#drawerBody{max-height:calc(70dvh - 54px)!important;overflow:auto!important;-webkit-overflow-scrolling:touch!important;padding:12px!important}.card{border-radius:17px!important;background:rgba(255,255,255,.045)!important;border-color:rgba(255,255,255,.10)!important}.row2{gap:10px!important}.btn{min-height:40px!important;border-radius:14px!important;background:rgba(255,255,255,.075)!important}.btn:disabled{opacity:.36!important}
#pickOverlay{padding:12px!important;z-index:140!important;background:rgba(0,0,0,.60)!important;backdrop-filter:blur(9px)!important;-webkit-backdrop-filter:blur(9px)!important}#pickPanel{width:100%!important;max-width:720px!important;max-height:78dvh!important;overflow:auto!important;border-radius:24px!important;background:linear-gradient(180deg,rgba(4,22,36,.98),rgba(2,12,22,.98))!important;padding:14px!important;border:1px solid rgba(150,230,255,.16)!important}#choices{grid-template-columns:1fr!important;gap:10px!important}.pickCard{border-radius:17px!important;padding:12px!important;background:rgba(255,255,255,.055)!important}
#toast{top:max(10px,env(safe-area-inset-top))!important;right:max(10px,env(safe-area-inset-right))!important;max-width:250px!important;border-radius:16px!important;z-index:150!important;background:rgba(2,16,27,.90)!important}
#start{background:radial-gradient(circle at 50% 35%,#0b4764,#031827 72%)!important}#start .box{width:min(420px,90vw)!important;padding:18px!important;border-radius:24px!important;background:rgba(2,16,27,.72)!important;border:1px solid rgba(150,230,255,.14)!important;box-shadow:0 22px 70px rgba(0,0,0,.35)!important}#start h1{font-size:22px!important}#start p{font-size:12px!important}#btnStart{width:100%!important;justify-content:center!important;min-height:48px!important;border-radius:18px!important;background:linear-gradient(180deg,rgba(90,240,220,.30),rgba(50,170,255,.18))!important;border:1px solid rgba(120,240,255,.28)!important}
@media (orientation:landscape){#hud{width:100px!important;padding:6px 8px!important;border-radius:15px!important}#hud>.row{min-height:16px!important}#hud>.row span:last-child{font-size:11px!important}.bar{height:4px!important;margin:3px 0!important}#drawer{left:auto!important;width:min(430px,42vw)!important;right:max(10px,env(safe-area-inset-right))!important;max-height:82dvh!important}#drawerBody{max-height:calc(82dvh - 54px)!important}#choices{grid-template-columns:repeat(3,minmax(0,1fr))!important}}
`;
