/* Presentation for Quiet Valley 0.5: orders, character stories, rent and weather. */
'use strict';
const GameplayUI=(()=>{
 const G=ValleyGameplay;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const hearts=n=>'<span class="friend-hearts">'+Array.from({length:5},(_,i)=>i<n?'♥':'♡').join('')+'</span>';
 function itemList(items){return Object.entries(items).map(([k,n])=>`<span class="order-item ${n>(window.__QV_STATE__?.inventory?.[k]||0)?'missing':''}">${FarmSim.PRODUCTS[k].icon} ${n}</span>`).join('');}
 function orders(s,now=Date.now()){
  window.__QV_STATE__=s;const w=G.weather(s,now),ready=s.game.orders.filter(o=>G.canDeliver(s,o)).length,cost=G.refreshCost(s);
  let html=`<button class="close" data-close-modal aria-label="Закрыть окно">×</button><div class="eyebrow">РЫНОЧНАЯ ДОСКА · РЕПУТАЦИЯ ${s.game.reputation}</div><h2 id="modal-title">Заказы долины</h2><p>Заказы теперь связаны с конкретными жителями. Выполняя их, вы не только зарабатываете, но и строите отношения.</p><div class="order-dashboard"><div><small>ГОТОВО СЕЙЧАС</small><b>${ready} / ${s.game.orders.length}</b></div><div><small>СЕРИЯ</small><b>×${Math.max(1,s.game.streak||1)}</b></div><div><small>ВЫПОЛНЕНО</small><b>${s.game.ordersCompleted}</b></div><div><small>ПОГОДА</small><b>${w.icon} ${w.name}</b></div></div><div class="orders-list">`;
  for(const o of s.game.orders){const p=G.orderPreview(s,o,now),left=Math.max(0,Math.ceil((o.bonusUntil-now)/1000)),can=G.canDeliver(s,o),ch=o.charId&&G.CHARACTERS[o.charId];html+=`<article class="order-card ${can?'ready':''}"><div class="order-avatar">${ch?ch.icon:o.icon}</div><div class="order-copy"><small>${esc(o.customer)}${ch?' · '+hearts(G.relationship(s,o.charId)):''}</small><h3>${esc(o.title)}</h3><div class="order-items">${itemList(o.items)}</div><div class="order-pay"><b>${p.reward} 🪙</b><span>+${o.xp} опыта · +${o.rep} реп.</span>${p.rush?`<em>⚡ премия ещё ${left}с</em>`:'<em class="muted">обычная цена</em>'}</div></div><button class="primary" data-action="deliverOrder" data-id="${o.id}" ${can?'':'disabled'}>${can?'Отправить':'Собрать'}</button></article>`;}
  html+=`</div><div class="order-footer"><button class="secondary" data-action="refreshOrders" ${s.coins<cost?'disabled':''}>Обновить доску · ${cost} 🪙</button><button class="secondary" data-open-people>Жители ♥</button><button class="secondary" data-open-journal>История →</button></div><div class="notice">⚡ Быстрый заказ: +25%. Дружба с Мией и Леей постепенно повышает оплату их заказов. Фёдор снижает цену обновления доски.</div>`;delete window.__QV_STATE__;return html;
 }
 function journal(s){const st=G.storyStatus(s),speaker=st.speaker&&G.CHARACTERS[st.speaker];let html=`<button class="close" data-close-modal aria-label="Закрыть окно">×</button><div class="eyebrow">ИСТОРИЯ ТИХОЙ ДОЛИНЫ · ГЛАВА ${Math.min(st.index+1,G.STORY.length)} / ${G.STORY.length}</div><h2 id="modal-title">${st.icon} ${st.title}</h2>`;
  if(speaker)html+=`<div class="story-speaker"><span>${speaker.icon}</span><div><b>${speaker.name} · ${speaker.role}</b><q>${esc(st.quote||G.characterDialogue(s,st.speaker))}</q></div></div>`;
  html+=`<p>${st.text}</p>`;
  if(st.complete){html+=`<div class="story-complete"><span>🏆</span><h3>Главная история завершена</h3><p>Вы подняли ферму и стали частью долины. Теперь отношения, аренда, хозяйство и оформление продолжаются в свободном режиме.</p><b>${s.game.ordersCompleted} заказов · ${s.game.reputation} репутации · ${s.animals.length} животных</b></div>`;}
  else{html+='<div class="story-list">';for(const r of st.requirements)html+=`<div class="story-goal ${r.done?'done':''}"><span>${r.done?'✓':'○'}</span><div><b>${r.text}</b><small>${Math.min(r.value,r.target)} / ${r.target}</small></div><div class="story-meter"><i style="width:${Math.min(100,r.value/r.target*100)}%"></i></div></div>`;html+=`</div><div class="story-reward"><span>Награда главы</span><b>${st.reward.coins} 🪙 · ${st.reward.wood} 🪵 · ${st.reward.stone} 🪨 · +${st.reward.rep} реп.</b></div><button class="primary" data-action="claimStory" data-id="${st.index}" ${st.ready?'':'disabled'}>${st.ready?'Завершить главу':'Продолжить играть'}</button>`;}
  html+=`<div class="order-footer"><button class="secondary" data-open-orders>← К заказам</button><button class="secondary" data-open-people>Жители ♥</button></div>`;return html;
 }
 function people(s){let html=`<button class="close" data-close-modal aria-label="Закрыть окно">×</button><div class="eyebrow">ЛЮДИ ТИХОЙ ДОЛИНЫ</div><h2 id="modal-title">Знакомые лица</h2><p>Дружба растёт от реальных поступков: заказов, развития долины и своевременной аренды. Просто нажимать «поговорить» бесконечно бесполезно.</p><div class="people-grid">`;
  for(const [id,c] of Object.entries(G.CHARACTERS)){const h=G.relationship(s,id);html+=`<article class="person-card" style="--person:${c.color}"><div class="person-portrait">${c.icon}</div><div class="person-copy"><small>${esc(c.role)}</small><h3>${esc(c.name)}</h3>${hearts(h)}<p>${esc(G.characterDialogue(s,id))}</p><em>${esc(G.characterPerk(s,id))}</em></div><button class="secondary" data-action="talkCharacter" data-key="${id}">Поговорить</button></article>`;}
  html+=`</div><div class="order-footer"><button class="secondary" data-open-lease>Договор аренды 🏠</button><button class="secondary" data-open-orders>Заказы →</button></div>`;return html;
 }
 function lease(s){const l=G.leaseStatus(s),el=G.relationship(s,'elena'),due=l.debt>0;let html=`<button class="close" data-close-modal aria-label="Закрыть окно">×</button><div class="eyebrow">ДОГОВОР С ЕЛЕНОЙ · НЕДЕЛЯ ${l.week}</div><h2 id="modal-title">🏠 Аренда фермы</h2><div class="lease-hero"><div><small>СЕГОДНЯ</small><b>День ${l.day}</b><span>день ${l.dayInWeek} из 7</span></div><div><small>СТАВКА</small><b>${l.price} 🪙</b><span>за игровую неделю</span></div><div><small>ДОВЕРИЕ</small><b>${hearts(el)}</b><span>${el>=3?'скидка −10 🪙':'скидка откроется на 3 ♥'}</span></div></div>`;
  if(l.free)html+=`<div class="lease-status good"><span>✓</span><div><b>Первая неделя бесплатная</b><p>Елена дала вам время освоиться. Первая оплата появится с 8-го игрового дня.</p></div></div>`;
  else if(due)html+=`<div class="lease-status due"><span>!</span><div><b>К оплате ${l.debt} монет</b><p>Штрафов, процентов и выселения нет. Сначала заработайте спокойно — долг не растёт.</p></div></div><button class="primary" data-action="payRent" ${s.coins<l.debt?'disabled':''}>Оплатить аренду · ${l.debt} 🪙</button>${s.coins<l.debt?`<div class="fineprint">Не хватает ${l.debt-s.coins} монет. Выполните пару заказов — Елена подождёт.</div>`:''}`;
  else html+=`<div class="lease-status good"><span>✓</span><div><b>Аренда за эту неделю оплачена</b><p>Следующая оплата появится только в начале следующей игровой недели.</p></div></div>`;
  html+=`<div class="rent-rules"><b>Мы не делаем бухгалтерский симулятор 😅</b><span>Один регулярный расход: аренда. Без электричества, налогов, страховок, процентов и случайных штрафов.</span></div><div class="order-footer"><button class="secondary" data-open-people>← К жителям</button></div>`;return html;
 }
 function intro(){return `<div class="intro-card"><div class="intro-kicker">ТИХАЯ ДОЛИНА · НАЧАЛО</div><div class="intro-person">👩‍🌾</div><h1>Новая жизнь на старой ферме</h1><blockquote>«Попробуйте пожить здесь неделю. Первый срок — бесплатно. Если место вам подойдёт, договоримся дальше.»<cite>— Елена, хозяйка земли</cite></blockquote><div class="intro-terms"><span><b>7 дней</b><small>первая неделя бесплатно</small></span><span><b>55 🪙</b><small>потом раз в неделю</small></span><span><b>без штрафов</b><small>долг не растёт</small></span></div><p>Вы приехали почти без денег, но с рабочей фермой, несколькими животными и соседями, которые готовы покупать продукцию. Развивайте хозяйство в своём темпе и постепенно становитесь частью долины.</p><button class="intro-start" data-action="markIntroSeen">Взять ключи от фермы →</button><small class="intro-foot">В прототипе один игровой день = 2 минуты активной игры. Пока вкладка закрыта, аренда не начисляется.</small></div>`;}
 return {orders,journal,people,lease,intro};
})();
