import { InputController, type MoveVector } from "./input/InputController";
import { PrisonScene, type InteractableId } from "./rendering/PrisonScene";
import { LocalSaveRepository, type SaveRepository } from "../persistence/SaveRepository";
import type { GameSnapshot, PlayerZone } from "../simulation/model";
import { capturePlayer, craftServiceShim, reachMaintenance, searchLocker, searchWorkshopBin, tickSimulation, unlockServiceHatch } from "../simulation/state";
export type RuntimeView={snapshot:GameSnapshot;playerZone:PlayerZone;nearby:InteractableId|null;prompt:string|null;message:string|null;guardWatching:boolean};
type Subscriber=(view:RuntimeView)=>void;
const PROMPTS:Record<InteractableId,string>={locker:"E · Осмотреть шкафчик","workshop-bin":"E · Осмотреть ящик мастерской","service-hatch":"E · Проверить служебный люк"};
export class GameRuntime{readonly input=new InputController();private readonly scene:PrisonScene;private readonly saves:SaveRepository;private readonly subscribers=new Set<Subscriber>();private snapshot:GameSnapshot;private view:RuntimeView;private raf=0;private previousAt=performance.now();private lastSavedAt=0;private messageExpiresAt=0;private stopped=false;
constructor(container:HTMLElement,saves:SaveRepository=new LocalSaveRepository()){this.saves=saves;this.snapshot=saves.load();this.scene=new PrisonScene(container);this.scene.setServiceHatchUnlocked(this.snapshot.flags.serviceHatchUnlocked);this.view={snapshot:this.snapshot,playerZone:"cell",nearby:null,prompt:null,message:"Первый день. Через несколько минут — перекличка.",guardWatching:false};this.messageExpiresAt=performance.now()+4200;}
start(){this.input.attach();this.previousAt=performance.now();this.raf=requestAnimationFrame(this.frame);}stop(){if(this.stopped)return;this.stopped=true;cancelAnimationFrame(this.raf);this.input.detach();this.saves.save(this.snapshot);this.scene.dispose();this.subscribers.clear();}subscribe(fn:Subscriber){this.subscribers.add(fn);fn(this.view);return()=>this.subscribers.delete(fn);}setVirtualMovement(v:MoveVector){this.input.setVirtual(v);}interact(){this.input.queueInteract();}craft(){const r=craftServiceShim(this.snapshot);this.apply(r.snapshot);this.message(r.message);}resetProgress(){this.saves.clear();location.reload();}
private apply(n:GameSnapshot){this.snapshot=n;this.scene.setServiceHatchUnlocked(n.flags.serviceHatchUnlocked);}private message(text:string,duration=3000){this.view={...this.view,message:text};this.messageExpiresAt=performance.now()+duration;}private interactWith(id:InteractableId){if(id==="locker"){const r=searchLocker(this.snapshot);this.apply(r.snapshot);this.message(r.message);return;}if(id==="workshop-bin"){const r=searchWorkshopBin(this.snapshot);this.apply(r.snapshot);this.message(r.message);return;}const r=unlockServiceHatch(this.snapshot);this.apply(r.snapshot);this.message(r.message);}
private frame=(now:number)=>{if(this.stopped)return;const elapsed=Math.min((now-this.previousAt)/1000,.1);this.previousAt=now;const f=this.scene.update(this.input.movement());this.snapshot=tickSimulation(this.snapshot,elapsed,{playerZone:f.playerZone,guardCanSeePlayer:f.guardCanSeePlayer});if(this.input.consumeInteract()&&f.nearestInteractable)this.interactWith(f.nearestInteractable);if(f.playerZone==="maintenance"&&this.snapshot.flags.serviceHatchUnlocked&&!this.snapshot.flags.firstRouteComplete){this.snapshot=reachMaintenance(this.snapshot);this.message("Маршрут найден. Теперь ты знаешь путь в служебный сектор. +25 монет · +10 репутации",5200);}if(this.snapshot.stats.suspicion>=100||f.guardDistance<.62){this.snapshot=capturePlayer(this.snapshot);this.scene.resetPlayerToCell();this.message("Тебя остановила охрана. После обыска ты снова в камере.",4200);}if(this.view.message&&now>this.messageExpiresAt)this.view={...this.view,message:null};this.view={...this.view,snapshot:this.snapshot,playerZone:f.playerZone,nearby:f.nearestInteractable,prompt:f.nearestInteractable?PROMPTS[f.nearestInteractable]:null,guardWatching:f.guardCanSeePlayer};if(now-this.lastSavedAt>1800){this.saves.save(this.snapshot);this.lastSavedAt=now;}for(const fn of this.subscribers)fn(this.view);this.raf=requestAnimationFrame(this.frame);};}
