'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const X=require('../src/expansion.js'),S=X.sim;
const NOW=1700000000000;
function fresh(region='farm'){const s=S.fresh(NOW);s.world.region=region;return s;}
function rich(region='farm'){const s=fresh(region);s.coins=10000;s.world.materials={wood:500,stone:500};return s;}
function act(s,a,t=NOW){return S.act(s,a,t);}
function build(s,key){assert.equal(act(s,{type:'upgrade',key}).ok,true,key);}
function tree(s){build(s,'orchard_clear');assert.equal(act(s,{type:'plantTree',id:0}).ok,true);}
function cell(s){for(let x=-12;x<=12;x+=2)for(let z=-10;z<=10;z+=2)if(!X.placementCheck(s,s.world.region,x,z))return {x,z};throw Error('No free cells');}
test('v2 starts with 16 home + 8 locked river beds and four regions',()=>{const s=fresh();assert.equal(s.version,2);assert.equal(s.plots.length,24);assert(s.plots.slice(16).every(p=>!p.unlocked));assert.equal(Object.keys(X.regions).length,4);});
test('v1 migration preserves money, animals, inventory and timers',()=>{const s=fresh();const old={...s,version:1,plots:s.plots.slice(0,16)};delete old.world;old.coins=435;old.inventory.carrot=19;const migrated=S.validate(old,NOW);assert.equal(migrated.coins,435);assert.equal(migrated.inventory.carrot,19);assert.deepEqual(migrated.animals,old.animals);assert.deepEqual(migrated.plots.slice(0,16),old.plots);assert.deepEqual(migrated.world.materials,{wood:8,stone:6});});
test('malformed or future save versions are rejected, not guessed',()=>{for(const raw of [null,{}, {...fresh(),version:9},{...fresh(),plots:[]}])assert.throws(()=>S.validate(raw,NOW));});
test('travel is free and invalid locations cannot change the current island',()=>{const s=fresh();const coins=s.coins;for(const region of Object.keys(X.regions))assert(act(s,{type:'travel',region}).ok);assert.equal(s.coins,coins);assert(!act(s,{type:'travel',region:'__proto__'}).ok);assert.equal(s.world.region,'forest');});
test('upgrade charges exact resources once and respects max level',()=>{const s=rich();const c=X.projectCost(s,'farm_paths');build(s,'farm_paths');assert.equal(s.coins,10000-c.coins);assert.equal(s.world.materials.stone,500-c.stone);const snapshot=JSON.stringify(s);assert(!act(s,{type:'upgrade',key:'farm_paths'}).ok);assert.equal(JSON.stringify(s),snapshot);});
test('unaffordable construction never partially spends materials',()=>{const s=fresh();s.coins=0;const material={...s.world.materials};assert(!act(s,{type:'upgrade',key:'farm_paths'}).ok);assert.deepEqual(s.world.materials,material);assert.equal(X.level(s,'farm_paths'),0);});
test('bridge is required before building river terraces',()=>{const s=rich('river');assert(!act(s,{type:'upgrade',key:'river_fields'}).ok);build(s,'river_bridge');build(s,'river_fields');assert(s.plots.slice(16).every(p=>p.unlocked));});
test('cannot unlock a river bed with the home 55-coin shortcut',()=>{const s=rich('river');const before=s.coins;assert(!act(s,{type:'unlock',id:16}).ok);assert.equal(s.coins,before);});
test('region authority rejects other islands farming and construction actions',()=>{const s=rich('orchard');assert(!act(s,{type:'water',id:2}).ok);assert(!act(s,{type:'upgrade',key:'farm_paths'}).ok);assert(!act(s,{type:'buyAnimal',species:'cow'}).ok);});
test('farm irrigation waters existing dry crops and newly planted beds',()=>{const s=rich();build(s,'farm_paths');build(s,'farm_water');assert.equal(s.plots[2].waterAt,NOW);assert(act(s,{type:'plant',id:7,crop:'carrot'}).ok);assert.equal(s.plots[7].readyAt,NOW+45000);});
test('soil levels shorten only NEW growth cycles, capped at 30%',()=>{const s=rich();act(s,{type:'plant',id:7,crop:'wheat'});act(s,{type:'water',id:7});const old=s.plots[7].readyAt;build(s,'farm_soil');build(s,'farm_soil');assert.equal(s.plots[7].readyAt,old);assert(!act(s,{type:'upgrade',key:'farm_soil'}).ok);act(s,{type:'plant',id:8,crop:'wheat'});act(s,{type:'water',id:8});assert.equal(s.plots[8].readyAt,NOW+21000);});
test('watering a growing bed cannot reset its timer',()=>{const s=rich();act(s,{type:'water',id:2});const ready=s.plots[2].readyAt;act(s,{type:'water',id:2},NOW+5000);assert.equal(s.plots[2].readyAt,ready);});
test('clearing changes terrain and awards material exactly once',()=>{const s=fresh('forest');const n=X.resourceNodes.find(n=>n.region==='forest'),before=s.world.materials[n.type];assert(act(s,{type:'clear',key:n.key}).ok);assert.equal(s.world.materials[n.type],before+n.amount);assert(!act(s,{type:'clear',key:n.key}).ok);assert.equal(s.world.materials[n.type],before+n.amount);});
test('materials can be replenished by coins, invalid quantities rejected',()=>{const s=fresh();const before=s.coins;assert(act(s,{type:'buyMaterial',key:'wood',qty:5}).ok);assert.equal(s.coins,before-15);assert.equal(s.world.materials.wood,13);for(const qty of [-1,0,.5,21,Infinity])assert(!act(s,{type:'buyMaterial',key:'stone',qty}).ok);});
test('an orchard tree requires clearing, a seedling and one watering',()=>{const s=rich('orchard');assert(!act(s,{type:'plantTree',id:0}).ok);tree(s);assert.equal(s.world.trees[0].waterAt,0);assert(act(s,{type:'waterTree',id:0}).ok);assert.equal(s.world.trees[0].readyAt,NOW+70000);assert(!act(s,{type:'harvestTree',id:0},NOW+69999).ok);assert(act(s,{type:'harvestTree',id:0},NOW+70000).ok);assert.equal(s.inventory.apple,3);assert(s.world.trees[0].planted);assert.equal(s.world.trees[0].waterAt,0);});
test('trees reject prototype keys and out-of-range IDs',()=>{const s=rich('orchard');build(s,'orchard_clear');for(const id of ['__proto__','constructor','0',-1,6,1.5]){assert(!act(s,{type:'plantTree',id}).ok);assert(!act(s,{type:'waterTree',id}).ok);assert(!act(s,{type:'harvestTree',id}).ok);}assert.equal(Array.prototype.planted,undefined);});
test('orchard irrigation starts the next cycle after harvesting',()=>{const s=rich('orchard');tree(s);build(s,'orchard_water');assert.equal(s.world.trees[0].waterAt,NOW);act(s,{type:'harvestTree',id:0},NOW+70000);assert.equal(s.world.trees[0].readyAt,NOW+140000);});
test('apple growth advances while visiting a different island',()=>{const s=rich('orchard');tree(s);act(s,{type:'waterTree',id:0});act(s,{type:'travel',region:'river'},NOW+30000);S.tick(s,NOW+71000);act(s,{type:'travel',region:'orchard'},NOW+71000);assert(act(s,{type:'harvestTree',id:0},NOW+71000).ok);});
test('apiary ticks offline, caps production, and cannot bank stock beyond capacity',()=>{const s=rich('forest');build(s,'forest_apiary');S.tick(s,NOW+45000);assert.equal(s.world.apiaryStock,1);S.tick(s,NOW+8*3600000);assert.equal(s.world.apiaryStock,3);act(s,{type:'collectHoney'},NOW+8*3600000);assert.equal(s.inventory.honey,3);S.tick(s,NOW+8*3600000+44999);assert.equal(s.world.apiaryStock,0);});
test('beekeeper cabin doubles capacity and has a prerequisite',()=>{const s=rich('forest');assert(!act(s,{type:'upgrade',key:'forest_cabin'}).ok);build(s,'forest_apiary');build(s,'forest_cabin');S.tick(s,NOW+45000*10);assert.equal(s.world.apiaryStock,6);});
test('new products sell at published prices; construction materials do not sell',()=>{const s=fresh();s.inventory.apple=3;s.inventory.honey=2;const coins=s.coins,wood=s.world.materials.wood;act(s,{type:'sell',key:'apple',qty:3});act(s,{type:'sell',key:'honey',qty:2});assert.equal(s.coins,coins+36+52);assert.equal(s.world.materials.wood,wood);});
test('each island has real, buildable decoration cells',()=>{for(const region of Object.keys(X.regions)){const s=rich(region),p=cell(s);assert(act(s,{type:'placeDecor',key:'flowers',region,...p}).ok);assert.equal(s.world.decor.length,1);}});
test('placement rejects waterways, structures, occupied cells and non-grid positions',()=>{const s=rich('river');for(const pos of [{x:0,z:0},{x:4,z:0},{x:-4.5,z:2},{x:NaN,z:0}])assert(!act(s,{type:'placeDecor',key:'tree',region:'river',...pos}).ok);const p=cell(s);act(s,{type:'placeDecor',key:'bench',region:'river',...p});assert(!act(s,{type:'placeDecor',key:'tree',region:'river',...p}).ok);});
test('dismantling refunds half and cannot be claimed twice',()=>{const s=rich();const p=cell(s),coins=s.coins;act(s,{type:'placeDecor',key:'bench',region:'farm',...p});const id=s.world.decor[0].id;assert(act(s,{type:'removeDecor',id}).ok);assert.equal(s.coins,coins-9);assert(!act(s,{type:'removeDecor',id}).ok);});
test('roundtrip retains regions, projects, cleared nodes, trees and decorations',()=>{const s=rich('orchard');tree(s);act(s,{type:'waterTree',id:0});act(s,{type:'clear',key:'orchard0'});const p=cell(s);act(s,{type:'placeDecor',key:'lamp',region:'orchard',rotation:2,...p});const restored=S.validate(JSON.parse(JSON.stringify(s)),NOW);assert.deepEqual(restored.world,s.world);assert.deepEqual(restored.inventory,s.inventory);});
test('tampered imports prune impossible projects and overlapping decorations',()=>{const s=rich();s.world.projects={river_fields:1,forest_cabin:1,farm_soil:999,constructor:5};const p=cell(s);s.world.decor=[{id:1,region:'farm',type:'tree',...p,rotation:9},{id:2,region:'farm',type:'bench',...p,rotation:0},{id:3,region:'farm',type:'__proto__',x:0,z:0}];const t=S.validate(s,NOW);assert.equal(X.level(t,'river_fields'),0);assert.equal(X.level(t,'forest_cabin'),0);assert.equal(X.level(t,'farm_soil'),2);assert.equal(t.world.decor.length,1);assert.equal(t.world.decor[0].rotation,3);});
test('every upgrade has a bounded cost and a valid dependency',()=>{for(const [key,p] of Object.entries(X.projects)){assert(X.regions[p.region]);assert(p.coins>=0&&p.wood>=0&&p.stone>=0&&p.max>=1);if(p.requires)assert(X.projects[p.requires]);}});
test('all projects can be completed in dependency order without invalid balances',()=>{const s=rich();for(const [key,p] of Object.entries(X.projects)){act(s,{type:'travel',region:p.region});for(let k=0;k<p.max;k++)build(s,key);}assert(s.coins>=0);assert(s.world.materials.wood>=0);assert(s.world.materials.stone>=0);assert.equal(s.plots.filter(p=>p.unlocked).length,20);});
