'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const G=require('../src/gameplay.js'),X=require('../src/expansion.js'),S=X.sim;
const NOW=1_800_000_000_000;
const act=(s,a,t=NOW)=>S.act(s,a,t);
function rich(region='farm'){const s=S.fresh(NOW);s.world.region=region;s.coins=10000;s.world.materials={wood:500,stone:500};return s;}
function build(s,key,t=NOW){assert(act(s,{type:'upgrade',key},t).ok,key);}
test('v4 starts with three curated market orders and a story chapter',()=>{const s=S.fresh(NOW);assert.equal(s.version,4);assert.equal(s.game.orders.length,3);assert.deepEqual(s.game.orders.map(o=>o.key),['bakery','grocer','dairy']);assert.equal(G.storyStatus(s).title,'Первые покупатели');});
test('first bakery order is immediately deliverable but consumes real inventory',()=>{const s=S.fresh(NOW),o=s.game.orders[0];assert(G.canDeliver(s,o));const before=s.coins,r=G.orderPreview(s,o,NOW);const out=act(s,{type:'deliverOrder',id:o.id});assert(out.ok);assert.equal(s.inventory.wheat,2);assert.equal(s.inventory.egg,0);assert.equal(s.coins,before+r.reward);assert.equal(s.game.ordersCompleted,1);assert.equal(s.game.reputation,1);assert.equal(s.game.orders.length,3);});
test('orders reject delivery without goods and never create negative inventory',()=>{const s=S.fresh(NOW),o=s.game.orders[1];s.inventory.carrot=0;const snap=JSON.stringify(s.inventory);assert(!act(s,{type:'deliverOrder',id:o.id}).ok);assert.equal(JSON.stringify(s.inventory),snap);});
test('fast consecutive deliveries build a capped streak and increase payout',()=>{const s=S.fresh(NOW);s.coins=0;for(let round=0;round<7;round++){const o=s.game.orders[0];for(const [k,n] of Object.entries(o.items))s.inventory[k]=Math.max(s.inventory[k]||0,n);assert(act(s,{type:'deliverOrder',id:o.id},NOW+round*10000).ok);}assert.equal(s.game.streak,5);assert.equal(s.game.ordersCompleted,7);assert(s.coins>400);});
test('order board refresh costs 15 coins and resets streak',()=>{const s=S.fresh(NOW);s.game.streak=4;const ids=s.game.orders.map(o=>o.id),coins=s.coins;assert(act(s,{type:'refreshOrders'}).ok);assert.equal(s.coins,coins-15);assert.equal(s.game.streak,0);assert.equal(s.game.orders.length,3);assert.notDeepEqual(s.game.orders.map(o=>o.id),ids);});
test('rain automatically waters open dry crops and empty soil',()=>{const s=S.fresh(NOW);act(s,{type:'plant',id:7,crop:'wheat'},NOW);assert.equal(S.status(s.plots[7],NOW),'dry');S.tick(s,NOW+G.WEATHER_MS);assert(s.plots[7].waterAt>0);assert(s.plots[7].readyAt>NOW+G.WEATHER_MS);assert(S.moisture(s.plots[8],NOW+G.WEATHER_MS)>.9);});
test('sun gives one extra crop at harvest without resetting the plot',()=>{const s=S.fresh(NOW);act(s,{type:'plant',id:7,crop:'wheat'},NOW);act(s,{type:'water',id:7},NOW);const before=s.inventory.wheat;assert(act(s,{type:'harvest',id:7},NOW+30000).ok);assert.equal(s.inventory.wheat,before+5);assert.equal(s.plots[7].crop,null);});
test('breeze adds one honey when collecting from a built apiary',()=>{const s=rich('forest');build(s,'forest_apiary');s.world.apiaryStock=1;s.world.apiaryAt=NOW+G.WEATHER_MS*2;const before=s.inventory.honey;const t=NOW+G.WEATHER_MS*2+1000;assert.equal(G.weather(s,t).key,'breeze');assert(act(s,{type:'collectHoney'},t).ok);assert.equal(s.inventory.honey,before+2);assert.equal(s.game.honeyCollected,2);});
test('story chapter reward can be claimed exactly once',()=>{const s=S.fresh(NOW);s.game.ordersCompleted=2;s.stats.harvests=5;const st=G.storyStatus(s);assert(st.ready);const before=s.coins;assert(act(s,{type:'claimStory',id:0}).ok);assert.equal(s.game.story,1);assert.equal(s.coins,before+100);assert(!act(s,{type:'claimStory',id:0}).ok);});
test('reputation unlocks harder order templates only when their production exists',()=>{const s=rich('orchard');s.game.reputation=20;build(s,'orchard_clear');act(s,{type:'plantTree',id:0});s.game.orders=[];s.game.orderCursor=8;G.ensureOrders(s,NOW);assert(s.game.orders.some(o=>o.key==='orchard'||o.key==='cider'));assert(!s.game.orders.some(o=>o.key==='honey'));});
test('v2 save migrates to v4 without losing expansion progress',()=>{const current=rich('river');build(current,'river_bridge');const old={...current,version:2};delete old.game;old.coins=4321;const restored=S.validate(JSON.parse(JSON.stringify(old)),NOW);assert.equal(restored.version,4);assert.equal(restored.coins,4321);assert.equal(X.level(restored,'river_bridge'),1);assert.equal(restored.game.orders.length,3);});
test('v4 roundtrip keeps orders, reputation, story and weather epoch',()=>{const s=S.fresh(NOW);const o=s.game.orders[0];act(s,{type:'deliverOrder',id:o.id});s.game.story=2;s.game.weatherStartedAt=NOW-12345;const r=S.validate(JSON.parse(JSON.stringify(s)),NOW);assert.equal(r.version,4);assert.equal(r.game.reputation,s.game.reputation);assert.equal(r.game.story,2);assert.equal(r.game.weatherStartedAt,NOW-12345);assert.deepEqual(r.game.orders,s.game.orders);});
test('tampered orders are pruned and regenerated safely',()=>{const s=S.fresh(NOW);s.game.orders=[{id:1,key:'__proto__'},{id:-4,key:'bakery'},null];const r=S.validate(JSON.parse(JSON.stringify(s)),NOW);assert.equal(r.game.orders.length,3);assert(r.game.orders.every(o=>G.ORDER_TEMPLATES[o.key]));});
