import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createDomain} from '../src/domain/createDomain.js';
const manifest=JSON.parse(fs.readFileSync(new URL('../dist/manifest.json',import.meta.url)));
const prefix='../dist/assets/'+manifest.sourceHash;
const {GameSession}=await import(prefix+'/application/session.js');
const {createSaveRepository,SAVE_KEY,BACKUP_KEY}=await import(prefix+'/infrastructure/saveRepository.js');
const {parseCommand}=await import(prefix+'/application/commands.js');
const NOW=1900000000000;
function memory(initial=[]){const map=new Map(initial);return {map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,String(v))};}
function setup(storage=memory()){let now=NOW;const clock={now:()=>now},d=createDomain(clock),repo=createSaveRepository(storage),s=new GameSession(d.commands,clock,repo);return {s,d,clock,storage,setTime:v=>{now=v;}};}

test('fresh farm retains 24 beds, four regions and five original animals',()=>{const {s,d}=setup();assert.equal(s.snapshot().plots.length,24);assert.equal(s.snapshot().animals.length,5);assert.equal(Object.keys(d.queries.FarmExpansion.regions).length,4);assert.equal(s.snapshot().coins,180);});
test('each session has independent feature composition',()=>{const a=setup(),b=setup();a.s.dispatch({type:'plant',id:7,crop:'wheat'});assert.equal(b.s.snapshot().plots[7].crop,null);assert.equal(b.s.snapshot().coins,180);});
test('snapshot and nested state cannot be mutated by UI',()=>{const {s}=setup();assert.throws(()=>s.snapshot().coins=99999,TypeError);assert.throws(()=>s.snapshot().inventory.wheat=99999,TypeError);assert.equal(s.snapshot().coins,180);});
test('crop cycle plants, waters and harvests through commands',()=>{const {s,setTime}=setup();assert.ok(s.dispatch({type:'plant',id:7,crop:'wheat'}).ok);assert.ok(s.dispatch({type:'water',id:7}).ok);setTime(NOW+31000);assert.ok(s.dispatch({type:'harvest',id:7}).ok);assert.equal(s.snapshot().plots[7].crop,null);assert.ok(s.snapshot().inventory.wheat>=10);});
test('repeated water does not reset readiness',()=>{const {s,setTime}=setup();s.dispatch({type:'plant',id:7,crop:'wheat'});s.dispatch({type:'water',id:7});const end=s.snapshot().plots[7].readyAt;setTime(NOW+5000);s.dispatch({type:'water',id:7});assert.equal(s.snapshot().plots[7].readyAt,end);});
test('insufficient money is atomic',()=>{const {s}=setup();const before=s.exportJSON();assert.equal(s.dispatch({type:'buyAnimal',species:'cow'}).ok,false);assert.equal(s.exportJSON(),before);});
test('feeding spends one wheat and improves hunger',()=>{const {s}=setup();const hunger=s.snapshot().animals[0].hunger;assert.ok(s.dispatch({type:'feed',id:1}).ok);assert.equal(s.snapshot().inventory.wheat,5);assert.ok(s.snapshot().animals[0].hunger>hunger);});
test('invalid and unknown command fields are rejected',()=>{assert.throws(()=>parseCommand({type:'water',id:7,coins:1000}));assert.throws(()=>parseCommand({type:'setCoins',coins:1000}));assert.throws(()=>parseCommand({type:'sell',qty:-1}));});
test('same request id cannot spend twice in one session',()=>{const {s}=setup();const a=s.dispatch({type:'plant',id:7,crop:'wheat'},'request-1');assert.ok(a.ok);const coins=s.snapshot().coins;assert.deepEqual(s.dispatch({type:'plant',id:7,crop:'wheat'},'request-1'),a);assert.equal(s.snapshot().coins,coins);assert.equal(s.dispatch({type:'plant',id:8,crop:'wheat'},'request-1').code,'idempotency-conflict');});
test('stale session revision fails before mutation',()=>{const {s}=setup();s.dispatch({type:'plant',id:7,crop:'wheat'});assert.equal(s.dispatch({type:'water',id:7},undefined,0).code,'revision-conflict');});
test('legacy save is migrated with exact raw backup',()=>{const d=createDomain({now:()=>NOW}),raw=JSON.stringify(d.commands.fresh(NOW));const storage=memory([['quiet-valley.v4',raw]]);const {s}=setup(storage);assert.equal(storage.getItem(BACKUP_KEY),raw);assert.ok(s.save().ok);assert.ok(storage.getItem(SAVE_KEY));});
test('corrupt canonical save is not silently replaced',()=>{const storage=memory([[SAVE_KEY,'{bad-json']]);const {s}=setup(storage);assert.equal(s.save().ok,false);assert.equal(storage.getItem(SAVE_KEY),'{bad-json');assert.equal(s.persistence().blocked,true);});
test('unavailable storage is a recoverable local session',()=>{const {s}=setup({getItem(){throw Error('unavailable');},setItem(){throw Error('unavailable');}});assert.ok(s.snapshot().plots);assert.equal(s.save().ok,false);assert.ok(JSON.parse(s.exportJSON()).plots);});
test('two tabs cannot silently overwrite another save',()=>{const storage=memory(),a=setup(storage),b=setup(storage);assert.ok(a.s.save().ok);b.s.dispatch({type:'plant',id:7,crop:'wheat'});assert.equal(b.s.save().conflict,true);});
test('import failure leaves current session unchanged',()=>{const {s}=setup();const before=s.exportJSON();assert.throws(()=>s.importJSON('{bad'));assert.equal(s.exportJSON(),before);});
test('save/reload preserves inventory and planted crops',()=>{const a=setup();a.s.dispatch({type:'plant',id:7,crop:'pumpkin'});a.s.save();const b=setup(a.storage);assert.equal(b.s.snapshot().coins,a.s.snapshot().coins);assert.equal(b.s.snapshot().plots[7].crop,'pumpkin');});
test('all four original regions can be visited',()=>{const {s}=setup();for(const region of ['orchard','river','forest','farm']){assert.ok(s.dispatch({type:'travel',region}).ok);assert.equal(s.snapshot().world.region,region);}});
test('old orchard clearing and apple planting still work',()=>{const {s}=setup();s.dispatch({type:'travel',region:'orchard'});assert.ok(s.dispatch({type:'upgrade',key:'orchard_clear'}).ok);assert.ok(s.dispatch({type:'plantTree',id:0}).ok);assert.ok(s.dispatch({type:'waterTree',id:0}).ok);assert.ok(s.snapshot().world.trees[0].waterAt);});
test('mill queue reserves ingredients and claims output once',()=>{const {s,setTime}=setup();assert.ok(s.dispatch({type:'buildWorkshop',key:'mill'}).ok);assert.ok(s.dispatch({type:'craft',key:'flour'}).ok);assert.equal(s.snapshot().inventory.wheat,3);const id=s.snapshot().production.jobs[0].id;setTime(NOW+26000);assert.ok(s.dispatch({type:'collectCraft',id}).ok);assert.equal(s.snapshot().inventory.flour,2);assert.equal(s.dispatch({type:'collectCraft',id}).ok,false);});
test('lease does not accrue for closed-game time on resume',()=>{const {s,setTime}=setup();const played=s.snapshot().game.playedMs;setTime(NOW+86400000);s.advance(true);assert.equal(s.snapshot().game.playedMs,played);assert.equal(s.snapshot().game.rentDebt,0);});
test('closed sessions reject commands',()=>{const {s}=setup();s.dispose();assert.equal(s.dispatch({type:'water',id:7}).code,'disposed');});
test('single material path has no iPhone flat-art override',()=>{const f=fs.readFileSync(new URL('../src/rendering/renderer.js',import.meta.url),'utf8');assert.equal(/userAgent|mobileSafe/.test(f),false);assert.ok(f.includes('shadowFragment'));});
test('restored scene has original mill, market, ducks and articulated animal legs',()=>{const f=fs.readFileSync(new URL('../src/scene/farm.js',import.meta.url),'utf8');for(const token of ['sails','ducks','legs','market','windmill'])assert.ok(f.toLowerCase().includes(token.toLowerCase()));assert.ok(f.length>19000);});
test('built HTML points at external versioned modules, not inline game source',()=>{const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');assert.ok(html.includes('assets/'+manifest.sourceHash+'/app/bootstrap.js'));assert.equal(html.includes('class Renderer'),false);assert.equal(html.includes('globalThis.FarmSim'),false);});
