import React, { useEffect } from "react";

export function HudPolishOverlay() {
  useEffect(() => {
    const applyPanelScrollMode = () => {
      const root = document.querySelector<HTMLElement>(".efNextPlay");
      const panel = document.querySelector<HTMLElement>(".efGamePanel");
      if (!root) return;
      root.style.touchAction = panel ? "auto" : "none";
      if (panel) {
        panel.style.overflowY = "auto";
        panel.style.touchAction = "pan-y";
        panel.style.setProperty("-webkit-overflow-scrolling", "touch");
      }
    };

    const observer = new MutationObserver(applyPanelScrollMode);
    applyPanelScrollMode();
    observer.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ["class", "style"] });
    const tick = window.setInterval(applyPanelScrollMode, 350);
    return () => {
      observer.disconnect();
      window.clearInterval(tick);
      const root = document.querySelector<HTMLElement>(".efNextPlay");
      if (root) root.style.touchAction = "none";
    };
  }, []);

  return (
    <style>{`
      .efQuickBar button:first-child,.efGamePanel.mapPanel{display:none!important}
      .efQuickBar{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important;width:min(252px,calc(var(--ef-vw,100vw) - 24px))!important;padding:8px!important;box-sizing:border-box!important;align-items:stretch!important;justify-items:stretch!important;border-radius:24px!important;transform:none!important;clip-path:none!important}
      .efQuickBar button{width:100%!important;min-width:0!important;min-height:42px!important;height:42px!important;padding:0 14px!important;border-radius:18px!important;box-sizing:border-box!important;display:flex!important;align-items:center!important;justify-content:center!important;transform:none!important;clip-path:none!important;line-height:1!important;text-align:center!important}
      .efNextHud{width:min(300px,calc(var(--ef-vw,100vw) - 24px))!important;max-height:168px!important;padding:8px 8px 6px!important;border-radius:0!important;background:transparent!important;border:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;gap:3px!important;overflow:visible!important;transform:none!important;clip-path:none!important}
      .efHudTitle{justify-content:flex-start!important;gap:8px!important}.efHudTitle b{font-size:16px!important;letter-spacing:.01em!important;text-shadow:0 2px 7px rgba(0,0,0,.50)!important}.efHudTitle em{font-size:9px!important;color:#fff3a0!important;text-shadow:0 2px 7px rgba(0,0,0,.50)!important;margin-left:auto!important}.efHudChips{display:flex!important;gap:5px!important;align-items:center!important;grid-template-columns:none!important}.efHudChips span{min-height:23px!important;min-width:auto!important;width:auto!important;padding:0 8px!important;border-radius:999px!important;font-size:10.5px!important;background:rgba(2,16,27,.20)!important;border:1px solid rgba(150,230,255,.13)!important;box-shadow:none!important;backdrop-filter:blur(5px)!important;-webkit-backdrop-filter:blur(5px)!important;transform:none!important;clip-path:none!important}.efHudChips span:nth-child(3),.efHudChips span:nth-child(4){background:rgba(2,16,27,.16)!important;border-color:rgba(255,255,255,.12)!important}.efHudLine{font-size:9px!important;line-height:1.12!important;color:rgba(231,242,255,.82)!important;text-shadow:0 2px 7px rgba(0,0,0,.52)!important}.efHudLine:nth-of-type(1),.efHudLine:nth-of-type(3){display:none!important}.efNextHud .questText{display:block!important;color:rgba(255,243,160,.90)!important;margin-top:2px!important}.efNextHud>i{height:3px!important;max-width:244px!important;border-radius:999px!important;background:transparent!important;box-shadow:none!important;overflow:visible!important;margin:1px 0 4px!important}.efNextHud>i em{display:block!important;height:100%!important;border-radius:999px!important;box-shadow:none!important}.efNextHud>i em:not(.xp):not(.quest):not(.apex){background:linear-gradient(90deg,#80ffd8,#68e9ff)!important}.efNextHud>i em.xp{background:linear-gradient(90deg,#f1cc73,#e59d3c)!important;box-shadow:none!important}.efNextHud>i em.quest{background:linear-gradient(90deg,#aa8bff,#765cff)!important;opacity:.78!important;box-shadow:none!important}.efNextHud>i em.apex{background:linear-gradient(90deg,#ff7474,#ffd36a)!important;box-shadow:none!important}.efNextHud.compact{width:min(250px,calc(var(--ef-vw,100vw) - 24px))!important;max-height:112px!important}
      .efMenuGrid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important;align-items:stretch!important;justify-items:stretch!important}.efMenuGrid button:first-child{display:none!important}.efMenuGrid button,.efControlModes button,.efShopTabs button,.efZoomPresets button,.efSettingRow button,.efWideButton,.efPanelHead button{transform:none!important;clip-path:none!important;box-sizing:border-box!important;appearance:none!important;-webkit-appearance:none!important;display:flex!important;align-items:center!important;justify-content:center!important;text-align:center!important;line-height:1.05!important;letter-spacing:0!important}.efMenuGrid button{width:100%!important;min-height:48px!important;height:48px!important;border-radius:16px!important;padding:0 10px!important}.efControlModes,.efShopTabs,.efZoomPresets{display:grid!important;gap:6px!important;align-items:stretch!important;justify-items:stretch!important}.efControlModes{grid-template-columns:repeat(3,minmax(0,1fr))!important}.efControlModes.two{grid-template-columns:repeat(2,minmax(0,1fr))!important}.efShopTabs,.efZoomPresets{grid-template-columns:repeat(3,minmax(0,1fr))!important}.efControlModes button,.efShopTabs button,.efZoomPresets button{width:100%!important;min-width:0!important;min-height:38px!important;height:38px!important;border-radius:14px!important;padding:0 8px!important;font-size:11px!important}.efSettingRow{transform:none!important;clip-path:none!important;border-radius:16px!important}.efSettingRow button{min-width:70px!important;height:34px!important;border-radius:999px!important}.efPanelHead{align-items:center!important;gap:10px!important;transform:none!important;clip-path:none!important}.efPanelHead button{width:34px!important;height:34px!important;min-width:34px!important;border-radius:50%!important;padding:0!important}.efShopCard,.efPanelItem,.efQuestItem,.efSettingBlock{transform:none!important;clip-path:none!important;box-sizing:border-box!important}.efShopCard{border-radius:16px!important;min-height:0!important}.efGamePanel{overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;touch-action:pan-y!important;overscroll-behavior:contain!important;max-height:min(74dvh,calc(var(--ef-vh,100dvh) - max(84px,env(safe-area-inset-top)) - 24px))!important;transform:none!important;clip-path:none!important}.efGamePanel *{touch-action:pan-y!important}.efSettingsPanel,.efShopPanel,.efFullMapPanel{max-height:calc(min(74dvh,calc(var(--ef-vh,100dvh) - max(84px,env(safe-area-inset-top)) - 24px)) - 52px)!important;overflow-y:auto!important;-webkit-overflow-scrolling:touch!important;touch-action:pan-y!important;padding-bottom:20px!important}.efControlModes,.efZoomPresets,.efPanelHead,.efSettingRow{touch-action:manipulation!important}.efSettingBlock,.efZoomControl{touch-action:pan-y!important}
      @media(max-width:520px){.efNextHud{width:min(292px,calc(var(--ef-vw,100vw) - 18px))!important;left:max(10px,env(safe-area-inset-left))!important;top:max(8px,env(safe-area-inset-top))!important}.efHudChips span{font-size:10px!important;min-height:22px!important;padding:0 7px!important}.efHudLine{font-size:8.8px!important}.efHudTitle b{font-size:15px!important}.efNextHud>i{max-width:232px!important}.efQuickBar{left:max(12px,env(safe-area-inset-left))!important;width:min(238px,calc(var(--ef-vw,100vw) - 24px))!important}.efQuickBar button{height:40px!important;min-height:40px!important}.efGamePanel{left:max(8px,env(safe-area-inset-left))!important;right:max(8px,env(safe-area-inset-right))!important;width:auto!important;max-height:min(78dvh,calc(var(--ef-vh,100dvh) - 86px))!important}.efSettingsPanel,.efShopPanel,.efFullMapPanel{max-height:calc(min(78dvh,calc(var(--ef-vh,100dvh) - 86px)) - 52px)!important}.efControlModes button,.efShopTabs button,.efZoomPresets button{height:36px!important;min-height:36px!important;font-size:10.5px!important}}
    `}</style>
  );
}
