import React from "react";

export function MapModalFixOverlay() {
  return (
    <style>{`
      .efGamePanel.mapPanel{position:fixed!important;left:50%!important;top:50%!important;right:auto!important;bottom:auto!important;transform:translate(-50%,-50%)!important;width:min(94vw,860px)!important;height:min(78dvh,760px)!important;max-height:min(78dvh,760px)!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;border-radius:24px!important;background:rgba(4,18,30,.88)!important;border:1px solid rgba(150,230,255,.20)!important;box-shadow:0 22px 68px rgba(0,0,0,.42)!important;backdrop-filter:blur(14px)!important;-webkit-backdrop-filter:blur(14px)!important;padding:0!important}.efGamePanel.mapPanel .efPanelHead{height:64px!important;flex:0 0 64px!important;padding:0 16px!important;border-bottom:1px solid rgba(150,230,255,.14)!important;background:rgba(2,16,27,.34)!important}.efGamePanel.mapPanel .efPanelHead b{font-size:23px!important}.efGamePanel.mapPanel .efPanelHead button{width:44px!important;height:44px!important;border-radius:50%!important}.efGamePanel.mapPanel .efFullMapPanel{position:relative!important;flex:1 1 auto!important;min-height:0!important;height:auto!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;padding:0!important;margin:0!important;max-height:none!important}.efGamePanel.mapPanel .efWorldMapFrame{position:relative!important;flex:1 1 auto!important;min-height:0!important;width:100%!important;height:100%!important;overflow:hidden!important;border:0!important;border-radius:0!important;background:rgba(2,16,27,.42)!important}.efGamePanel.mapPanel .efWorldMapSvg{display:block!important;width:100%!important;height:100%!important;min-width:0!important;max-width:none!important}.efGamePanel.mapPanel .efMapLegend{position:absolute!important;left:12px!important;right:12px!important;bottom:10px!important;display:flex!important;flex-wrap:wrap!important;gap:8px!important;justify-content:center!important;padding:8px 10px!important;border-radius:14px!important;background:rgba(2,16,27,.54)!important;backdrop-filter:blur(10px)!important;-webkit-backdrop-filter:blur(10px)!important;z-index:2!important}.efGamePanel.mapPanel .efMapLegend span{font-size:11px!important}@media(max-width:720px){.efGamePanel.mapPanel{width:calc(100vw - 12px)!important;height:min(79dvh,760px)!important;border-radius:22px!important}.efGamePanel.mapPanel .efPanelHead{height:58px!important;flex-basis:58px!important}.efGamePanel.mapPanel .efPanelHead b{font-size:22px!important}.efGamePanel.mapPanel .efMapLegend{display:none!important}}
    `}</style>
  );
}
