import React from "react";

/**
 * Lightweight panel styling for mobile performance.
 * One scroll container for all panels: Menu, Settings, Shop, Quests, Mutations, Craft.
 */
export function PanelPerformanceOverlay() {
  return (
    <style>{`
      .efGamePanel:not(.mapPanel){position:fixed!important;left:max(10px,env(safe-area-inset-left))!important;right:max(10px,env(safe-area-inset-right))!important;top:calc(max(10px,env(safe-area-inset-top)) + 132px)!important;bottom:calc(max(104px,env(safe-area-inset-bottom)) + 76px)!important;width:auto!important;max-width:none!important;height:auto!important;max-height:none!important;margin:0!important;padding:10px!important;display:block!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior:contain!important;border-radius:22px!important;background:rgba(2,16,27,.92)!important;border:1px solid rgba(120,220,255,.20)!important;box-shadow:0 14px 36px rgba(0,0,0,.34)!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;clip-path:none!important;transform:none!important;contain:layout paint!important;touch-action:pan-y!important;z-index:16000!important;scrollbar-width:thin!important;scroll-padding-top:54px!important}
      .efGamePanel:not(.mapPanel)::-webkit-scrollbar{width:4px!important}.efGamePanel:not(.mapPanel)::-webkit-scrollbar-thumb{background:rgba(150,230,255,.34)!important;border-radius:999px!important}.efGamePanel:not(.mapPanel) *{box-sizing:border-box!important;touch-action:pan-y!important}.efGamePanel:not(.mapPanel) button,.efGamePanel:not(.mapPanel) a,.efGamePanel:not(.mapPanel) input{touch-action:manipulation!important}
      .efPanelHead{position:sticky!important;top:0!important;z-index:5!important;height:42px!important;min-height:42px!important;margin:-10px -10px 10px!important;padding:10px 10px 8px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;border-bottom:1px solid rgba(120,220,255,.14)!important;background:linear-gradient(180deg,rgba(2,16,27,.98),rgba(2,16,27,.86))!important;box-shadow:0 10px 24px rgba(0,0,0,.18)!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
      .efPanelHead b{font-size:18px!important;line-height:1!important;font-weight:1000!important;color:#fff!important;text-shadow:none!important}.efPanelHead button{width:40px!important;height:40px!important;min-width:40px!important;border-radius:50%!important;padding:0!important;font-size:26px!important;line-height:1!important;display:flex!important;align-items:center!important;justify-content:center!important}
      .efMenuGrid,.efSettingsPanel,.efShopPanel{display:grid!important;min-height:0!important;max-height:none!important;overflow:visible!important;padding:0 0 12px!important;margin:0!important}.efMenuGrid{grid-template-columns:repeat(2,minmax(0,1fr))!important;align-content:start!important;gap:10px!important}.efMenuGrid button:first-child{display:none!important}.efMenuGrid button{height:58px!important;min-height:58px!important;border-radius:18px!important;font-size:13px!important;font-weight:1000!important}
      .efSettingsPanel{gap:8px!important}.efSettingBlock,.efSettingRow,.efZoomControl{border-radius:14px!important;padding:9px!important;margin:0!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(120,220,255,.13)!important;box-shadow:none!important}.efSettingBlock{display:grid!important;gap:7px!important}.efSettingBlock b{font-size:12px!important;line-height:1.05!important}.efSettingBlock small{display:none!important}.efControlModes,.efShopTabs,.efZoomPresets{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:6px!important}.efControlModes.two{grid-template-columns:repeat(2,minmax(0,1fr))!important}.efControlModes button,.efShopTabs button,.efZoomPresets button,.efWideButton,.efSettingRow button{height:34px!important;min-height:34px!important;border-radius:12px!important;padding:0 7px!important;font-size:10.5px!important;line-height:1!important}
      .efShopPanel{display:block!important}.efShopBalance{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important;margin:0 0 8px!important}.efShopBalance span{min-height:46px!important;border-radius:15px!important;background:rgba(255,255,255,.05)!important;border:1px solid rgba(120,220,255,.14)!important;box-shadow:none!important}.efShopTabs{position:sticky!important;top:42px!important;z-index:3!important;margin:0 0 8px!important;padding:4px 0!important;background:rgba(2,16,27,.94)!important}.efShopGrid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:9px!important;align-items:start!important}.efShopCard{min-height:178px!important;height:auto!important;padding:8px!important;border-radius:16px!important;background:rgba(1,12,23,.72)!important;border:1px solid rgba(120,220,255,.15)!important;box-shadow:none!important;display:grid!important;grid-template-rows:102px auto auto auto!important;align-items:center!important;justify-items:center!important;gap:4px!important;overflow:hidden!important;contain:layout paint!important}.efShopCard .efSkinPreview{width:100%!important;height:102px!important;max-height:102px!important;display:block!important;overflow:hidden!important;opacity:1!important;visibility:visible!important;position:relative!important;z-index:1!important}.efShopCard .efSkinPreview>svg,.efShopCard .efSkinShowcase{width:100%!important;height:102px!important;max-height:102px!important;display:block!important}.efShopCard b{font-size:12px!important;line-height:1.05!important;text-align:center!important}.efShopCard small,.efShopCard em{font-size:10px!important;line-height:1.05!important;text-align:center!important}.efShopPanel a{display:flex!important;height:38px!important;align-items:center!important;justify-content:center!important;border-radius:14px!important;margin-top:9px!important}
      .efPanelItem,.efQuestItem{position:relative!important;margin:0 0 8px!important;width:100%!important;padding:10px!important;border-radius:16px!important;background:linear-gradient(180deg,rgba(255,255,255,.052),rgba(255,255,255,.028))!important;border:1px solid rgba(120,220,255,.13)!important;box-shadow:none!important}.efPanelItem b,.efQuestItem b{font-size:12px!important;line-height:1.12!important;color:#f4fbff!important}.efPanelItem small,.efQuestItem small{font-size:11px!important;line-height:1.18!important;color:rgba(231,242,255,.66)!important}.efPanelItem em,.efQuestItem em{font-size:10.5px!important;line-height:1.1!important;color:rgba(255,243,160,.96)!important;font-style:normal!important;font-weight:1000!important}
      .efQuestItem{display:grid!important;grid-template-columns:1fr auto!important;grid-template-areas:"title progress" "desc progress" "reward reward"!important;gap:4px 10px!important;min-height:86px!important;padding:12px 12px 11px!important;touch-action:pan-y!important}.efQuestItem b{grid-area:title!important;display:block!important;padding-right:6px!important;font-size:13px!important}.efQuestItem b span{grid-area:progress!important;position:static!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;min-width:54px!important;height:28px!important;padding:0 9px!important;border-radius:999px!important;background:rgba(120,240,255,.10)!important;border:1px solid rgba(120,240,255,.20)!important;color:#78f0ff!important;font-size:12px!important;font-weight:1000!important;white-space:nowrap!important}.efQuestItem small{grid-area:desc!important;font-size:12px!important;line-height:1.2!important;display:block!important}.efQuestItem em{grid-area:reward!important;display:block!important;margin-top:1px!important;font-size:11px!important;line-height:1.12!important}.efQuestItem.done{border-color:rgba(110,255,180,.28)!important;background:linear-gradient(180deg,rgba(110,255,180,.07),rgba(255,255,255,.028))!important}.efQuestItem.done:after{content:"✓";position:absolute!important;right:10px!important;bottom:9px!important;width:19px!important;height:19px!important;border-radius:999px!important;display:grid!important;place-items:center!important;background:rgba(110,255,180,.14)!important;color:#80ffd8!important;font-size:12px!important;font-weight:1000!important}
      @media(max-width:520px){.efGamePanel:not(.mapPanel){left:max(8px,env(safe-area-inset-left))!important;right:max(8px,env(safe-area-inset-right))!important;top:calc(max(8px,env(safe-area-inset-top)) + 130px)!important;bottom:calc(max(100px,env(safe-area-inset-bottom)) + 72px)!important;padding:8px!important;border-radius:20px!important}.efPanelHead{height:38px!important;min-height:38px!important;margin:-8px -8px 9px!important;padding:8px 8px 7px!important}.efPanelHead b{font-size:16px!important}.efPanelHead button{width:38px!important;height:38px!important;min-width:38px!important}.efShopTabs{top:38px!important}.efShopCard{min-height:160px!important;grid-template-rows:88px auto auto auto!important}.efShopCard .efSkinPreview,.efShopCard .efSkinPreview>svg,.efShopCard .efSkinShowcase{height:88px!important;max-height:88px!important}.efMenuGrid button{height:52px!important;min-height:52px!important}.efQuestItem{min-height:80px!important;padding:10px!important}.efQuestItem b{font-size:12.5px!important}.efQuestItem small{font-size:11.5px!important}.efQuestItem b span{min-width:48px!important;height:26px!important;font-size:11px!important}}
    `}</style>
  );
}
