import React from "react";

/**
 * Lightweight panel styling for mobile performance.
 * Replaces expensive panel CSS layers: no :has(), no backdrop-filter, no heavy nested selectors.
 */
export function PanelPerformanceOverlay() {
  return (
    <style>{`
      .efGamePanel:not(.mapPanel){position:fixed!important;left:max(10px,env(safe-area-inset-left))!important;right:max(10px,env(safe-area-inset-right))!important;top:calc(max(10px,env(safe-area-inset-top)) + 132px)!important;bottom:calc(max(104px,env(safe-area-inset-bottom)) + 76px)!important;width:auto!important;max-width:none!important;height:auto!important;max-height:none!important;margin:0!important;padding:10px!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;border-radius:22px!important;background:rgba(2,16,27,.92)!important;border:1px solid rgba(120,220,255,.20)!important;box-shadow:0 14px 36px rgba(0,0,0,.34)!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;clip-path:none!important;transform:none!important;contain:layout paint!important;touch-action:pan-y!important;z-index:16000!important}
      .efPanelHead{position:relative!important;flex:0 0 42px!important;height:42px!important;min-height:42px!important;margin:0 0 8px!important;padding:0 0 8px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;border-bottom:1px solid rgba(120,220,255,.14)!important;background:transparent!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
      .efPanelHead b{font-size:18px!important;line-height:1!important;font-weight:1000!important;color:#fff!important;text-shadow:none!important}.efPanelHead button{width:40px!important;height:40px!important;min-width:40px!important;border-radius:50%!important;padding:0!important;font-size:26px!important;line-height:1!important;display:flex!important;align-items:center!important;justify-content:center!important;touch-action:manipulation!important}
      .efMenuGrid,.efSettingsPanel,.efShopPanel{flex:1 1 auto!important;min-height:0!important;max-height:none!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;overscroll-behavior:contain!important;touch-action:pan-y!important;scrollbar-width:thin!important;padding:0 0 12px!important;margin:0!important}
      .efMenuGrid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;align-content:start!important;gap:10px!important}.efMenuGrid button:first-child{display:none!important}.efMenuGrid button{height:58px!important;min-height:58px!important;border-radius:18px!important;font-size:13px!important;font-weight:1000!important;touch-action:manipulation!important}
      .efSettingsPanel{display:grid!important;gap:8px!important}.efSettingBlock,.efSettingRow,.efZoomControl{border-radius:14px!important;padding:9px!important;margin:0!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(120,220,255,.13)!important;box-shadow:none!important}.efSettingBlock{display:grid!important;gap:7px!important}.efSettingBlock b{font-size:12px!important;line-height:1.05!important}.efSettingBlock small{display:none!important}.efControlModes,.efShopTabs,.efZoomPresets{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:6px!important}.efControlModes.two{grid-template-columns:repeat(2,minmax(0,1fr))!important}.efControlModes button,.efShopTabs button,.efZoomPresets button,.efWideButton,.efSettingRow button{height:34px!important;min-height:34px!important;border-radius:12px!important;padding:0 7px!important;font-size:10.5px!important;line-height:1!important;touch-action:manipulation!important}
      .efShopPanel{display:block!important}.efShopBalance{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important;margin:0 0 8px!important}.efShopBalance span{min-height:46px!important;border-radius:15px!important;background:rgba(255,255,255,.05)!important;border:1px solid rgba(120,220,255,.14)!important;box-shadow:none!important}.efShopTabs{position:sticky!important;top:0!important;z-index:2!important;margin:0 0 8px!important;padding:4px 0!important;background:rgba(2,16,27,.92)!important}.efShopGrid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:9px!important;align-items:start!important}.efShopCard{min-height:178px!important;height:auto!important;padding:8px!important;border-radius:16px!important;background:rgba(1,12,23,.72)!important;border:1px solid rgba(120,220,255,.15)!important;box-shadow:none!important;display:grid!important;grid-template-rows:102px auto auto auto!important;align-items:center!important;justify-items:center!important;gap:4px!important;overflow:hidden!important;touch-action:manipulation!important;contain:layout paint!important}.efShopCard .efSkinPreview{width:100%!important;height:102px!important;max-height:102px!important;display:block!important;overflow:hidden!important;opacity:1!important;visibility:visible!important;position:relative!important;z-index:1!important}.efShopCard .efSkinPreview>svg,.efShopCard .efSkinShowcase{width:100%!important;height:102px!important;max-height:102px!important;display:block!important}.efShopCard b{font-size:12px!important;line-height:1.05!important;text-align:center!important}.efShopCard small,.efShopCard em{font-size:10px!important;line-height:1.05!important;text-align:center!important}.efShopPanel a{display:flex!important;height:38px!important;align-items:center!important;justify-content:center!important;border-radius:14px!important;margin-top:9px!important;touch-action:manipulation!important}
      .efPanelItem,.efQuestItem{margin:0 0 8px!important;width:100%!important;padding:10px!important;border-radius:16px!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(120,220,255,.13)!important;box-shadow:none!important;touch-action:manipulation!important}.efPanelItem b,.efQuestItem b{font-size:12px!important;line-height:1.12!important}.efPanelItem small,.efQuestItem small{font-size:11px!important;line-height:1.18!important}.efPanelItem em,.efQuestItem em{font-size:10.5px!important;line-height:1.1!important}
      @media(max-width:520px){.efGamePanel:not(.mapPanel){left:max(8px,env(safe-area-inset-left))!important;right:max(8px,env(safe-area-inset-right))!important;top:calc(max(8px,env(safe-area-inset-top)) + 130px)!important;bottom:calc(max(100px,env(safe-area-inset-bottom)) + 72px)!important;padding:8px!important;border-radius:20px!important}.efPanelHead{height:38px!important;min-height:38px!important;flex-basis:38px!important}.efPanelHead b{font-size:16px!important}.efPanelHead button{width:38px!important;height:38px!important;min-width:38px!important}.efShopCard{min-height:160px!important;grid-template-rows:88px auto auto auto!important}.efShopCard .efSkinPreview,.efShopCard .efSkinPreview>svg,.efShopCard .efSkinShowcase{height:88px!important;max-height:88px!important}.efMenuGrid button{height:52px!important;min-height:52px!important}}
    `}</style>
  );
}
