import React from "react";

/**
 * One hard layout contract for ALL in-game panels: Menu, Settings, Shop, Quests, Mutations, Craft.
 * CSS-only: no observers, no DOM writes, no runtime side effects.
 */
export function PanelHardLayoutOverlay() {
  return (
    <style>{`
      html body main.efNextPlay .efGamePanel:not(.mapPanel){position:fixed!important;left:max(8px,env(safe-area-inset-left))!important;right:max(8px,env(safe-area-inset-right))!important;top:calc(max(8px,env(safe-area-inset-top)) + 82px)!important;bottom:calc(max(116px,env(safe-area-inset-bottom)) + 64px)!important;width:auto!important;height:auto!important;max-width:none!important;max-height:none!important;margin:0!important;padding:8px!important;border-radius:18px!important;overflow:hidden!important;display:flex!important;flex-direction:column!important;background:linear-gradient(180deg,rgba(4,25,40,.94),rgba(1,12,23,.92))!important;border:1px solid rgba(150,230,255,.18)!important;box-shadow:0 18px 54px rgba(0,0,0,.42)!important;backdrop-filter:blur(13px)!important;-webkit-backdrop-filter:blur(13px)!important;box-sizing:border-box!important;z-index:20010!important;transform:none!important;clip-path:none!important;touch-action:pan-y!important;overscroll-behavior:contain!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) *{box-sizing:border-box!important;transform:none!important;clip-path:none!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efPanelHead{position:relative!important;top:auto!important;z-index:3!important;flex:0 0 38px!important;height:38px!important;min-height:38px!important;margin:0 0 7px!important;padding:0 0 7px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:10px!important;background:transparent!important;border-bottom:1px solid rgba(150,230,255,.13)!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efPanelHead b{font-size:15px!important;line-height:1!important;font-weight:1000!important;color:#fff!important;letter-spacing:.01em!important;text-shadow:none!important;margin:0!important;padding:0!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efPanelHead button{width:32px!important;height:32px!important;min-width:32px!important;border-radius:999px!important;padding:0!important;display:flex!important;align-items:center!important;justify-content:center!important;font-size:21px!important;line-height:1!important;background:rgba(255,255,255,.075)!important;border:1px solid rgba(255,255,255,.14)!important;color:#e7f2ff!important;box-shadow:none!important;touch-action:manipulation!important}

      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efMenuGrid{flex:1 1 auto!important;min-height:0!important;display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;align-content:start!important;gap:8px!important;margin:0!important;padding:0!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;touch-action:pan-y!important;overscroll-behavior:contain!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efMenuGrid button{height:48px!important;min-height:48px!important;max-height:48px!important;width:100%!important;margin:0!important;padding:0 10px!important;border-radius:15px!important;display:flex!important;align-items:center!important;justify-content:center!important;text-align:center!important;font-size:12px!important;line-height:1!important;font-weight:1000!important;color:#e7f2ff!important;background:linear-gradient(180deg,rgba(255,255,255,.075),rgba(255,255,255,.035))!important;border:1px solid rgba(150,230,255,.16)!important;box-shadow:none!important;touch-action:manipulation!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efMenuGrid button:first-child{display:none!important}

      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efSettingsPanel,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efShopPanel{flex:1 1 auto!important;min-height:0!important;height:auto!important;max-height:none!important;display:grid!important;grid-template-columns:1fr!important;align-content:start!important;gap:7px!important;margin:0!important;padding:0 1px 12px!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;touch-action:pan-y!important;overscroll-behavior:contain!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efSettingsPanel::-webkit-scrollbar,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efShopPanel::-webkit-scrollbar,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efMenuGrid::-webkit-scrollbar{width:0!important;height:0!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efSettingBlock{display:grid!important;gap:5px!important;min-height:0!important;margin:0!important;padding:7px!important;border-radius:12px!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(150,230,255,.115)!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:hidden!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efSettingBlock b{font-size:11.5px!important;line-height:1!important;font-weight:1000!important;color:#fff!important;margin:0!important;padding:0!important;letter-spacing:0!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efSettingBlock small{display:none!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efControlModes,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efShopTabs,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efZoomPresets{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:5px!important;margin:0!important;padding:0!important;min-height:0!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efControlModes.two{grid-template-columns:repeat(2,minmax(0,1fr))!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efControlModes button,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efShopTabs button,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efZoomPresets button,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efWideButton{height:29px!important;min-height:29px!important;max-height:29px!important;padding:0 5px!important;border-radius:10px!important;font-size:9.5px!important;line-height:1!important;font-weight:1000!important;display:flex!important;align-items:center!important;justify-content:center!important;text-align:center!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;background:rgba(255,255,255,.065)!important;border:1px solid rgba(150,230,255,.13)!important;color:#e7f2ff!important;box-shadow:none!important;touch-action:manipulation!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efControlModes button.active,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efShopTabs button.active{background:linear-gradient(180deg,rgba(120,240,255,.24),rgba(70,130,255,.10))!important;border-color:rgba(120,240,255,.38)!important;color:#fff!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efSettingRow{min-height:36px!important;margin:0!important;padding:5px 7px!important;border-radius:11px!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(150,230,255,.11)!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:7px!important;box-shadow:none!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efSettingRow span{font-size:10.5px!important;line-height:1!important;font-weight:900!important;color:#e7f2ff!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efSettingRow button{height:28px!important;min-height:28px!important;min-width:54px!important;border-radius:999px!important;font-size:9.5px!important;padding:0 8px!important;touch-action:manipulation!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efZoomControl{display:grid!important;gap:4px!important;margin:0!important;padding:7px!important;border-radius:11px!important;background:rgba(255,255,255,.04)!important;border:1px solid rgba(150,230,255,.105)!important;box-shadow:none!important;touch-action:pan-y!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efZoomControl span{font-size:10.5px!important;line-height:1!important;font-weight:850!important;color:rgba(231,242,255,.85)!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efZoomControl input{height:20px!important;margin:0!important;touch-action:manipulation!important;accent-color:#78f0ff!important}

      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efShopBalance{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:6px!important;margin:0!important;padding:0!important}.efShopBalance span{min-height:38px!important;border-radius:12px!important;font-size:11px!important}.efShopGrid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:7px!important}.efShopCard{min-height:116px!important;height:auto!important;padding:7px!important;border-radius:13px!important;font-size:10px!important}.efShopCard b{font-size:10.5px!important;line-height:1!important}.efShopCard small,.efShopCard em{font-size:9px!important;line-height:1!important}.efShopPanel a{height:34px!important;min-height:34px!important;border-radius:12px!important;font-size:10px!important}
      html body main.efNextPlay .efGamePanel:not(.mapPanel) .efPanelItem,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efQuestItem{display:grid!important;gap:4px!important;margin:0 0 6px!important;width:100%!important;padding:7px!important;border-radius:12px!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(150,230,255,.11)!important;box-shadow:none!important}.efPanelItem b,.efQuestItem b{font-size:11px!important;line-height:1.1!important}.efPanelItem small,.efQuestItem small{font-size:9.5px!important;line-height:1.15!important}.efPanelItem em,.efQuestItem em{font-size:9.5px!important;line-height:1!important}

      html body main.efNextPlay:has(.efGamePanel){touch-action:auto!important}
      @media(max-width:430px){html body main.efNextPlay .efGamePanel:not(.mapPanel){top:calc(max(6px,env(safe-area-inset-top)) + 72px)!important;left:max(5px,env(safe-area-inset-left))!important;right:max(5px,env(safe-area-inset-right))!important;bottom:calc(max(106px,env(safe-area-inset-bottom)) + 56px)!important;padding:6px!important;border-radius:15px!important}html body main.efNextPlay .efGamePanel:not(.mapPanel) .efPanelHead{height:34px!important;min-height:34px!important;flex-basis:34px!important;margin-bottom:5px!important}html body main.efNextPlay .efGamePanel:not(.mapPanel) .efPanelHead b{font-size:13px!important}html body main.efNextPlay .efGamePanel:not(.mapPanel) .efMenuGrid button{height:44px!important;min-height:44px!important;max-height:44px!important;font-size:11px!important}html body main.efNextPlay .efGamePanel:not(.mapPanel) .efSettingBlock{padding:6px!important;gap:4px!important}html body main.efNextPlay .efGamePanel:not(.mapPanel) .efControlModes button,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efShopTabs button,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efZoomPresets button,html body main.efNextPlay .efGamePanel:not(.mapPanel) .efWideButton{height:28px!important;min-height:28px!important;font-size:9px!important}.efShopCard{min-height:106px!important}}
    `}</style>
  );
}
