import React from "react";

/**
 * Hard visual/layout override for the in-game Settings panel.
 * CSS-only: no observers, no DOM writes, no runtime side effects.
 */
export function SettingsPanelCompactOverlay() {
  return (
    <style>{`
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel){position:fixed!important;top:max(4px,env(safe-area-inset-top))!important;left:max(6px,env(safe-area-inset-left))!important;right:max(6px,env(safe-area-inset-right))!important;bottom:auto!important;width:auto!important;height:auto!important;max-height:calc(100svh - max(8px,env(safe-area-inset-top)) - 8px)!important;padding:6px!important;border-radius:15px!important;overflow:hidden!important;display:flex!important;flex-direction:column!important;background:rgba(2,16,27,.94)!important;border:1px solid rgba(150,230,255,.16)!important;box-shadow:0 16px 44px rgba(0,0,0,.34)!important;backdrop-filter:blur(12px)!important;-webkit-backdrop-filter:blur(12px)!important;box-sizing:border-box!important;touch-action:pan-y!important;z-index:20020!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efPanelHead{position:relative!important;top:auto!important;z-index:2!important;flex:0 0 34px!important;height:34px!important;min-height:34px!important;margin:0 0 5px!important;padding:0 0 5px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;background:transparent!important;border-bottom:1px solid rgba(150,230,255,.12)!important;box-shadow:none!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efPanelHead b{font-size:13px!important;line-height:1!important;font-weight:1000!important;color:#fff!important;letter-spacing:0!important;text-shadow:none!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efPanelHead button{width:30px!important;height:30px!important;min-width:30px!important;border-radius:999px!important;padding:0!important;display:flex!important;align-items:center!important;justify-content:center!important;font-size:20px!important;line-height:1!important;background:rgba(255,255,255,.07)!important;border:1px solid rgba(255,255,255,.12)!important;color:#e7f2ff!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efSettingsPanel{flex:1 1 auto!important;min-height:0!important;height:auto!important;max-height:calc(100svh - max(8px,env(safe-area-inset-top)) - 55px)!important;display:grid!important;grid-template-columns:1fr!important;gap:6px!important;padding:0 1px 12px!important;margin:0!important;overflow-y:auto!important;overflow-x:hidden!important;-webkit-overflow-scrolling:touch!important;touch-action:pan-y!important;overscroll-behavior:contain!important;box-sizing:border-box!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efSettingsPanel::-webkit-scrollbar{width:0!important;height:0!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efSettingBlock{display:grid!important;grid-template-columns:1fr!important;gap:5px!important;min-height:0!important;margin:0!important;padding:7px!important;border-radius:11px!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(150,230,255,.11)!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;overflow:hidden!important;box-sizing:border-box!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efSettingBlock b{font-size:11.5px!important;line-height:1!important;font-weight:1000!important;color:#fff!important;margin:0!important;padding:0!important;letter-spacing:0!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efSettingBlock small{display:none!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efControlModes{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:5px!important;margin:0!important;padding:0!important;min-height:0!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efControlModes.two{grid-template-columns:repeat(2,minmax(0,1fr))!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efControlModes button,html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efZoomPresets button,html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efWideButton{height:29px!important;min-height:29px!important;max-height:29px!important;padding:0 5px!important;border-radius:10px!important;font-size:9.5px!important;line-height:1!important;font-weight:1000!important;display:flex!important;align-items:center!important;justify-content:center!important;text-align:center!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;background:rgba(255,255,255,.065)!important;border:1px solid rgba(150,230,255,.13)!important;color:#e7f2ff!important;box-shadow:none!important;touch-action:manipulation!important;box-sizing:border-box!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efControlModes button.active{background:linear-gradient(180deg,rgba(120,240,255,.23),rgba(70,130,255,.10))!important;border-color:rgba(120,240,255,.38)!important;color:#fff!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efSettingRow{min-height:36px!important;margin:0!important;padding:5px 7px!important;border-radius:11px!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(150,230,255,.11)!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:7px!important;box-shadow:none!important;box-sizing:border-box!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efSettingRow span{font-size:10.5px!important;line-height:1!important;font-weight:900!important;color:#e7f2ff!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efSettingRow button{height:28px!important;min-height:28px!important;min-width:54px!important;border-radius:999px!important;font-size:9.5px!important;padding:0 8px!important;touch-action:manipulation!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efZoomControl{display:grid!important;gap:4px!important;margin:0!important;padding:7px!important;border-radius:11px!important;background:rgba(255,255,255,.04)!important;border:1px solid rgba(150,230,255,.105)!important;box-shadow:none!important;touch-action:pan-y!important;box-sizing:border-box!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efZoomControl span{font-size:10.5px!important;line-height:1!important;font-weight:850!important;color:rgba(231,242,255,.85)!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efZoomControl input{height:20px!important;margin:0!important;touch-action:manipulation!important;accent-color:#78f0ff!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efZoomPresets{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:5px!important;margin:0!important;padding:0!important}
      html body main.efNextPlay .efGamePanel:has(.efSettingsPanel),html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) *{transform:none!important;clip-path:none!important}
      html body main.efNextPlay:has(.efGamePanel .efSettingsPanel){touch-action:auto!important}
      @media(max-width:430px){html body main.efNextPlay .efGamePanel:has(.efSettingsPanel){top:max(2px,env(safe-area-inset-top))!important;left:max(4px,env(safe-area-inset-left))!important;right:max(4px,env(safe-area-inset-right))!important;max-height:calc(100svh - max(4px,env(safe-area-inset-top)) - 6px)!important;padding:5px!important;border-radius:14px!important}html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efPanelHead{height:32px!important;min-height:32px!important;flex-basis:32px!important;margin-bottom:4px!important}html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efSettingsPanel{max-height:calc(100svh - max(4px,env(safe-area-inset-top)) - 46px)!important;gap:5px!important;padding-bottom:10px!important}html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efSettingBlock{padding:6px!important;gap:4px!important}html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efControlModes button,html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efZoomPresets button,html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efWideButton{height:28px!important;min-height:28px!important;font-size:9px!important}html body main.efNextPlay .efGamePanel:has(.efSettingsPanel) .efPanelHead b{font-size:12.5px!important}}
    `}</style>
  );
}
