import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,command,advance,step,restore} from '../dist/src/domain/simulation.js';
import {MAPS,SHIPS,STAGES} from '../dist/src/domain/catalog.js';
import {validPath,findRoute,clearPoint,clearSegment,nearestApproach,distance} from '../dist/src/domain/navigation.js';
const route=(s,id=s.ships[0].id)=>{const b=s.ships.find(b=>b.id===id),p=MAPS[s.mapId].ports.find(p=>p.id===b.kind);return command(s,{type:'route',id,path:findRoute(b,p,MAPS[s.mapId])});};
for(const map of MAPS)for(const kind of ['cargo','fishing','ferry'])test(`reachable ${map.id}/${kind} from all entries`,()=>{for(const e of map.entries){const p=map.ports.find(p=>p.id===kind),r=findRoute(e,p,map);assert.ok(r.length);assert.ok(validPath(e,r,map));assert.deepEqual(r.at(-1),{...r.at(-1)});}});
test('known deterministic initial state',()=>assert.deepEqual(createGame(0,91),createGame(0,91)));
test('fresh map is independent',()=>{const a=createGame(),b=createGame();a.ships[0].path[0].x=0;assert.notEqual(a.ships[0].path[0].x,b.ships[0].path[0].x);});
test('ship docks and rewards exactly once',()=>{const s=createGame();assert.ok(route(s).ok);advance(s,18);assert.equal(s.delivered,1);assert.ok(s.score>=120);const score=s.score;advance(s,2);assert.equal(s.score,score);});
test('wrong port rejected without changing route',()=>{const s=createGame(),old=structuredClone(s.ships[0].path),p=MAPS[0].ports[1];assert.equal(command(s,{type:'route',id:s.ships[0].id,path:findRoute(s.ships[0],p,MAPS[0])}).ok,false);assert.deepEqual(old,s.ships[0].path);});
test('route crossing island rejected',()=>{const s=createGame();assert.equal(command(s,{type:'route',id:1,path:[{x:-10,z:-6}]}).ok,false);});
test('nonfinite / oversize routes rejected',()=>{const s=createGame();for(const path of [[{x:NaN,z:0}],Array.from({length:161},()=>({x:0,z:0})),[{x:200,z:0}]])assert.equal(command(s,{type:'route',id:1,path}).ok,false);});
test('hold expires and movement resumes',()=>{const s=createGame();route(s);command(s,{type:'hold',id:1});const x=s.ships[0].x;advance(s,4);assert.equal(s.ships[0].x,x);advance(s,6);assert.notEqual(s.ships[0].x,x);assert.ok(s.ships[0].hold>=0);});
test('focus slows simulation but consumes real time',()=>{const s=createGame();assert.ok(command(s,{type:'focus'}).ok);advance(s,4);assert.ok(s.time>0.9&&s.time<1.1);assert.ok(s.focusLeft>1.9&&s.focusLeft<2.1);assert.equal(command(s,{type:'focus'}).ok,false);});
test('swept collision calculation',()=>assert.equal(nearestApproach({x:-2,z:0},{x:2,z:0},{x:2,z:0},{x:-2,z:0}),0));
test('one collision costs one safety point',()=>{const s=createGame();s.ships.push({...structuredClone(s.ships[0]),id:777});step(s,.03);assert.equal(s.strikes,1);assert.equal(s.ships.length,0);});
test('loss after three mistakes',()=>{const s=createGame();s.strikes=2;s.ships[0].age=99;step(s,.03);assert.equal(s.phase,'lost');const old=s.time;advance(s,5);assert.equal(s.time,old);});
test('rescue grants single reward',()=>{const s=createGame();s.rescue={id:998,x:s.ships[0].x,z:s.ships[0].z,remaining:27};step(s,.03);assert.equal(s.rescued,1);assert.equal(s.score,160);step(s,.03);assert.equal(s.score,160);});
test('missed SOS is not a safety strike',()=>{const s=createGame();s.rescue={id:998,x:0,z:7,remaining:.01};step(s,.03);assert.equal(s.strikes,0);assert.equal(s.rescue,null);});
test('upgrade gated by phase and only one choice',()=>{const s=createGame();assert.equal(command(s,{type:'upgrade',key:'speed'}).ok,false);s.phase='upgrade';assert.ok(command(s,{type:'upgrade',key:'speed'}).ok);assert.equal(s.upgrades.speed,1);assert.equal(s.stage,1);assert.equal(command(s,{type:'upgrade',key:'speed'}).ok,false);});
test('repair restores only one safety point',()=>{const s=createGame();s.phase='upgrade';s.strikes=2;command(s,{type:'upgrade',key:'repair'});assert.equal(s.strikes,1);});
test('save roundtrip does not advance time',()=>{const s=createGame();route(s);advance(s,3);const r=restore(JSON.parse(JSON.stringify(s)));assert.equal(r.time,s.time);assert.equal(r.ships[0].x,s.ships[0].x);assert.deepEqual(r.events,[]);});
test('future and corrupt saves rejected',()=>{for(const v of [null,{}, {...createGame(),version:9},{...createGame(),score:NaN},{...createGame(),ships:Array(20).fill({})}])assert.throws(()=>restore(v));});
test('bad map / unsafe restored path rejected',()=>{assert.throws(()=>createGame(99));const s=createGame();s.ships[0].path=[{x:-10,z:-6}];assert.throws(()=>restore(s));});
test('occupied entry defers spawn',()=>{const s=createGame();s.spawned=4;s.spawnClock=0;s.ships[0].path=[];advance(s,.5);assert.equal(s.ships.length,1);assert.equal(s.spawned,4);});
test('safe automatic planning can complete a whole expedition',()=>{const s=createGame(0,4554);for(let i=0;i<10000&&s.phase!=='won'&&s.phase!=='lost';i++){
 if(s.phase==='upgrade')command(s,{type:'upgrade',key:s.strikes?'repair':'speed'});
 for(const b of s.ships)if(b.age<.051)route(s,b.id);
 step(s,.05);
 }assert.equal(s.phase,'won');assert.ok(s.delivered>=22);assert.ok(s.score>3000);});
