import React from "react";
import { GameRuntime, type RuntimeView } from "./engine/GameRuntime";
import { ITEM_LABELS } from "./simulation/model";
import { formatClock, minutesUntilScheduleChange, scheduleAt } from "./simulation/schedule";
import "./breakout.css";

function useRuntime(runtime:GameRuntime|null){const[view,setView]=React.useState<RuntimeView|null>(null);React.useEffect(()=>(runtime?runtime.subscribe(setView):undefined),[runtime]);return view;}
function TouchControls({runtime}:{runtime:GameRuntime}){const set=(x:number,z:number)=>runtime.setVirtualMovement({x,z}),release=()=>set(0,0),bind=(x:number,z:number)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);set(x,z);},onPointerUp:release,onPointerCancel:release,onPointerLeave:(e:React.PointerEvent<HTMLButtonElement>)=>{if(e.buttons===0)release();}});return <div className="boTouch" aria-label="Сенсорное управление"><button className="u" {...bind(0,-1)}>▲</button><button className="l" {...bind(-1,0)}>◀</button><button className="r" {...bind(1,0)}>▶</button><button className="d" {...bind(0,1)}>▼</button></div>}
export function BreakoutGame(){const mount=React.useRef<HTMLDivElement|null>(null);const[runtime,setRuntime]=React.useState<GameRuntime|null>(null);const[started,setStarted]=React.useState(false);const[fatal,setFatal]=React.useState<string|null>(null);const view=useRuntime(runtime);
React.useEffect(()=>{if(!started||!mount.current)return;let game:GameRuntime|null=null;try{game=new GameRuntime(mount.current);game.start();setRuntime(game);}catch(error){setFatal(error instanceof Error?error.message:String(error));}return()=>{game?.stop();setRuntime(null);};},[started]);
const s=view?.snapshot,sch=s?scheduleAt(s.minuteOfDay):null;const canCraft=Boolean(s?.inventory.some(x=>x.itemId==="metal-strip")&&s.inventory.some(x=>x.itemId==="cloth-tape")&&!s.inventory.some(x=>x.itemId==="service-shim"));
return <main className="boApp"><div ref={mount} className="boViewport" aria-label="Изометрический тюремный блок"/>
{!started?<section className="boIntro"><div className="boCode">BLACKCROWN WORLD // 03</div><h1>BREAKOUT</h1><p className="lead">Закрытый исправительный комплекс «Сектор 17».</p><p>Здесь всё работает по расписанию. Отмечайся на обязательных мероприятиях, наблюдай за охраной и собирай сведения между проверками. В первом vertical slice нужно найти путь в служебный сектор.</p><div className="boRules"><span><b>WASD</b> движение</span><span><b>E</b> действие</span><span><b>1 сек</b> = 1 игровая минута</span></div><button className="boPrimary" onClick={()=>setStarted(true)}>ВОЙТИ В СЕКТОР 17</button><a href="/games/">← BLACKCROWN GAMES</a></section>:null}
{fatal?<section className="boFatal"><h2>3D-сцена не запустилась</h2><p>{fatal}</p><a href="/games/">Вернуться в Games</a></section>:null}
{started&&view&&s&&sch?<div className="boHud"><header className="boTop"><div className="boBrand"><span>BC</span><div><strong>BREAKOUT</strong><small>SECTOR 17 · VERTICAL SLICE</small></div></div><div className="boClock"><strong>ДЕНЬ {s.day} · {formatClock(s.minuteOfDay)}</strong><span>{sch.label} · ещё {Math.ceil(minutesUntilScheduleChange(s.minuteOfDay))} мин.</span></div></header>
<aside className="boObjectives"><em>ПЛАН // СЛУЖЕБНЫЙ МАРШРУТ</em><h2>Первый выход</h2>{s.objectives.map((o,i)=><div key={o.id} className={`boObjective ${o.completed?"done":""}`}><span>{o.completed?"✓":String(i+1).padStart(2,"0")}</span><p>{o.label}</p></div>)}</aside>
<aside className="boStatus"><div><span>ЗОНА</span><b>{view.playerZone.toUpperCase()}</b></div><div><span>ДЕНЬГИ</span><b>${s.stats.money}</b></div><div><span>РЕПУТАЦИЯ</span><b>{s.stats.reputation}</b></div><label><span>ПОДОЗРЕНИЕ</span><b>{Math.round(s.stats.suspicion)}%</b></label><div className="boMeter"><i style={{width:`${s.stats.suspicion}%`}}/></div>{view.guardWatching?<strong className="boWatch">● ОХРАНА НАБЛЮДАЕТ</strong>:null}</aside>
<section className="boInventory"><em>КАРМАНЫ</em><div className="boSlots">{s.inventory.length?s.inventory.map(slot=><div className="boSlot" key={slot.itemId}><span>{slot.itemId==="service-shim"?"⌁":"▰"}</span><div><b>{ITEM_LABELS[slot.itemId]}</b><small>×{slot.quantity}</small></div></div>):<div className="boEmpty">Пусто</div>}</div><button disabled={!canCraft} onClick={()=>runtime?.craft()}>{s.inventory.some(x=>x.itemId==="service-shim")?"СЕРВИСНЫЙ КЛЮЧ ГОТОВ":"СОБРАТЬ СЕРВИСНЫЙ КЛЮЧ"}</button></section>
{view.prompt?<button className="boPrompt" onClick={()=>runtime?.interact()}>{view.prompt}</button>:null}{view.message?<div className="boToast">{view.message}</div>:null}
{s.flags.firstRouteComplete?<section className="boComplete"><em>ROUTE DISCOVERED</em><h2>Служебный сектор найден.</h2><p>Это ещё не побег. Но теперь у тебя есть маршрут, который охрана считает закрытым. Следующий этап добавит NPC-сделки, работу, крафт и полноценные варианты побега.</p><button onClick={()=>runtime.resetProgress()}>ПРОЙТИ ЗАНОВО</button><a href="/games/">ВЕРНУТЬСЯ В ЛОББИ</a></section>:null}
<div className="boKeyboard">WASD / стрелки · E / Space действие</div>{runtime?<><TouchControls runtime={runtime}/><button className="boTouchE" onClick={()=>runtime.interact()}>E</button></>:null}</div>:null}</main>;
}
