create extension if not exists pgcrypto with schema extensions;

create or replace function public.blackcrown_bridge_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.blackcrown_accounts (
  id uuid primary key default gen_random_uuid(),
  site_user_id text not null unique
    check (site_user_id ~ '^[A-Za-z0-9_.:@-]{1,160}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.blackcrown_telegram_links (
  account_id uuid primary key
    references public.blackcrown_accounts(id) on delete cascade,
  telegram_user_id bigint not null unique check (telegram_user_id > 0),
  telegram_chat_id bigint not null check (telegram_chat_id > 0),
  telegram_username text
    check (telegram_username is null or telegram_username ~ '^[A-Za-z0-9_]{1,64}$'),
  linked_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (telegram_chat_id = telegram_user_id)
);

create table if not exists public.blackcrown_telegram_link_codes (
  code_hash text primary key check (code_hash ~ '^[0-9a-f]{64}$'),
  account_id uuid not null
    references public.blackcrown_accounts(id) on delete cascade,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now(),
  check (expires_at > created_at),
  check (consumed_at is null or consumed_at >= created_at)
);

create index if not exists blackcrown_link_codes_account_idx
  on public.blackcrown_telegram_link_codes(account_id, created_at desc);
create index if not exists blackcrown_link_codes_expiry_idx
  on public.blackcrown_telegram_link_codes(expires_at)
  where consumed_at is null;

create table if not exists public.blackcrown_entitlements (
  account_id uuid not null
    references public.blackcrown_accounts(id) on delete cascade,
  entitlement_key text not null
    check (entitlement_key ~ '^[a-z0-9._-]{1,80}$'),
  status text not null default 'active'
    check (status in ('active', 'revoked')),
  source text not null default 'system'
    check (source in ('payment', 'admin', 'promo', 'migration', 'system')),
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (account_id, entitlement_key),
  check (expires_at is null or expires_at > starts_at)
);

create index if not exists blackcrown_entitlements_active_idx
  on public.blackcrown_entitlements(account_id, entitlement_key)
  where status = 'active';

create table if not exists public.blackcrown_account_events (
  id bigint generated by default as identity primary key,
  account_id uuid
    references public.blackcrown_accounts(id) on delete set null,
  event_type text not null
    check (event_type ~ '^[a-z0-9._-]{1,80}$'),
  actor text not null default 'system'
    check (actor ~ '^[a-z0-9._-]{1,40}$'),
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists blackcrown_account_events_account_idx
  on public.blackcrown_account_events(account_id, id desc);

alter table public.blackcrown_accounts enable row level security;
alter table public.blackcrown_telegram_links enable row level security;
alter table public.blackcrown_telegram_link_codes enable row level security;
alter table public.blackcrown_entitlements enable row level security;
alter table public.blackcrown_account_events enable row level security;

revoke all on table public.blackcrown_accounts
  from public, anon, authenticated;
revoke all on table public.blackcrown_telegram_links
  from public, anon, authenticated;
revoke all on table public.blackcrown_telegram_link_codes
  from public, anon, authenticated;
revoke all on table public.blackcrown_entitlements
  from public, anon, authenticated;
revoke all on table public.blackcrown_account_events
  from public, anon, authenticated;
revoke all on sequence public.blackcrown_account_events_id_seq
  from public, anon, authenticated;

grant all on table public.blackcrown_accounts to service_role;
grant all on table public.blackcrown_telegram_links to service_role;
grant all on table public.blackcrown_telegram_link_codes to service_role;
grant all on table public.blackcrown_entitlements to service_role;
grant all on table public.blackcrown_account_events to service_role;
grant usage, select on sequence public.blackcrown_account_events_id_seq
  to service_role;

drop trigger if exists blackcrown_accounts_touch_updated_at
  on public.blackcrown_accounts;
create trigger blackcrown_accounts_touch_updated_at
before update on public.blackcrown_accounts
for each row execute function public.blackcrown_bridge_touch_updated_at();

drop trigger if exists blackcrown_telegram_links_touch_updated_at
  on public.blackcrown_telegram_links;
create trigger blackcrown_telegram_links_touch_updated_at
before update on public.blackcrown_telegram_links
for each row execute function public.blackcrown_bridge_touch_updated_at();

drop trigger if exists blackcrown_entitlements_touch_updated_at
  on public.blackcrown_entitlements;
create trigger blackcrown_entitlements_touch_updated_at
before update on public.blackcrown_entitlements
for each row execute function public.blackcrown_bridge_touch_updated_at();

create or replace function public.blackcrown_issue_telegram_link_code(
  p_site_user_id text,
  p_code_hash text,
  p_expires_at timestamptz
)
returns table(expires_at timestamptz)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_account_id uuid;
begin
  if p_site_user_id is null
     or p_site_user_id !~ '^[A-Za-z0-9_.:@-]{1,160}$' then
    raise exception using errcode = 'P0001', message = 'invalid_site_user_id';
  end if;
  if p_code_hash is null or p_code_hash !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = 'P0001', message = 'invalid_link_code_hash';
  end if;
  if p_expires_at <= now()
     or p_expires_at > now() + interval '15 minutes' then
    raise exception using errcode = 'P0001', message = 'invalid_link_expiry';
  end if;

  insert into public.blackcrown_accounts(site_user_id)
  values (p_site_user_id)
  on conflict (site_user_id) do update set updated_at = now()
  returning id into v_account_id;

  if exists (
    select 1
    from public.blackcrown_telegram_link_codes
    where account_id = v_account_id
      and consumed_at is null
      and expires_at > now()
      and created_at > now() - interval '15 seconds'
  ) then
    raise exception using errcode = 'P0001', message = 'link_rate_limited';
  end if;

  update public.blackcrown_telegram_link_codes
  set consumed_at = coalesce(consumed_at, now())
  where account_id = v_account_id
    and consumed_at is null;

  delete from public.blackcrown_telegram_link_codes
  where expires_at < now() - interval '1 day';

  insert into public.blackcrown_telegram_link_codes(
    code_hash,
    account_id,
    expires_at
  ) values (
    p_code_hash,
    v_account_id,
    p_expires_at
  );

  insert into public.blackcrown_account_events(
    account_id,
    event_type,
    actor,
    metadata
  ) values (
    v_account_id,
    'telegram.link_code_issued',
    'site',
    jsonb_build_object('expires_at', p_expires_at)
  );

  return query select p_expires_at;
end;
$$;

create or replace function public.blackcrown_consume_telegram_link_code(
  p_code_hash text,
  p_telegram_user_id bigint,
  p_telegram_chat_id bigint,
  p_telegram_username text default null
)
returns table(
  linked boolean,
  premium_active boolean,
  entitlement_keys text[]
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_code public.blackcrown_telegram_link_codes%rowtype;
  v_conflicting_account uuid;
  v_conflicting_telegram bigint;
  v_username text;
begin
  if p_code_hash is null or p_code_hash !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = 'P0001', message = 'invalid_or_expired_link_code';
  end if;
  if p_telegram_user_id is null
     or p_telegram_user_id <= 0
     or p_telegram_chat_id is null
     or p_telegram_chat_id <> p_telegram_user_id then
    raise exception using errcode = 'P0001', message = 'private_chat_required';
  end if;

  v_username := nullif(left(regexp_replace(
    coalesce(p_telegram_username, ''),
    '[^A-Za-z0-9_]',
    '',
    'g'
  ), 64), '');

  select * into v_code
  from public.blackcrown_telegram_link_codes
  where code_hash = p_code_hash
  for update;

  if not found
     or v_code.consumed_at is not null
     or v_code.expires_at <= now() then
    raise exception using errcode = 'P0001', message = 'invalid_or_expired_link_code';
  end if;

  select account_id into v_conflicting_account
  from public.blackcrown_telegram_links
  where telegram_user_id = p_telegram_user_id;

  if found and v_conflicting_account <> v_code.account_id then
    raise exception using errcode = 'P0001', message = 'telegram_already_linked';
  end if;

  select telegram_user_id into v_conflicting_telegram
  from public.blackcrown_telegram_links
  where account_id = v_code.account_id;

  if found and v_conflicting_telegram <> p_telegram_user_id then
    raise exception using errcode = 'P0001', message = 'account_already_linked';
  end if;

  insert into public.blackcrown_telegram_links(
    account_id,
    telegram_user_id,
    telegram_chat_id,
    telegram_username
  ) values (
    v_code.account_id,
    p_telegram_user_id,
    p_telegram_chat_id,
    v_username
  )
  on conflict (account_id) do update set
    telegram_user_id = excluded.telegram_user_id,
    telegram_chat_id = excluded.telegram_chat_id,
    telegram_username = excluded.telegram_username,
    updated_at = now();

  update public.blackcrown_telegram_link_codes
  set consumed_at = now()
  where code_hash = p_code_hash;

  insert into public.blackcrown_account_events(
    account_id,
    event_type,
    actor,
    metadata
  ) values (
    v_code.account_id,
    'telegram.linked',
    'telegram',
    jsonb_build_object(
      'telegram_user_id', p_telegram_user_id,
      'telegram_username', v_username
    )
  );

  return query
  select
    true,
    exists (
      select 1
      from public.blackcrown_entitlements e
      where e.account_id = v_code.account_id
        and e.entitlement_key = 'blackcrown.premium'
        and e.status = 'active'
        and e.starts_at <= now()
        and (e.expires_at is null or e.expires_at > now())
    ),
    coalesce((
      select array_agg(e.entitlement_key order by e.entitlement_key)
      from public.blackcrown_entitlements e
      where e.account_id = v_code.account_id
        and e.status = 'active'
        and e.starts_at <= now()
        and (e.expires_at is null or e.expires_at > now())
    ), array[]::text[]);
end;
$$;

create or replace function public.blackcrown_get_site_telegram_status(
  p_site_user_id text
)
returns table(
  linked boolean,
  telegram_username text,
  linked_at timestamptz,
  premium_active boolean,
  entitlement_keys text[]
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_account_id uuid;
begin
  select id into v_account_id
  from public.blackcrown_accounts
  where site_user_id = p_site_user_id;

  if not found then
    return query
    select false, null::text, null::timestamptz, false, array[]::text[];
    return;
  end if;

  return query
  select
    l.account_id is not null,
    l.telegram_username,
    l.linked_at,
    exists (
      select 1
      from public.blackcrown_entitlements e
      where e.account_id = v_account_id
        and e.entitlement_key = 'blackcrown.premium'
        and e.status = 'active'
        and e.starts_at <= now()
        and (e.expires_at is null or e.expires_at > now())
    ),
    coalesce((
      select array_agg(e.entitlement_key order by e.entitlement_key)
      from public.blackcrown_entitlements e
      where e.account_id = v_account_id
        and e.status = 'active'
        and e.starts_at <= now()
        and (e.expires_at is null or e.expires_at > now())
    ), array[]::text[])
  from (select v_account_id as account_id) a
  left join public.blackcrown_telegram_links l
    on l.account_id = a.account_id;
end;
$$;

create or replace function public.blackcrown_get_telegram_identity(
  p_telegram_user_id bigint
)
returns table(
  site_user_id text,
  premium_active boolean,
  entitlement_keys text[]
)
language sql
security definer
set search_path = public, extensions
stable
as $$
  select
    a.site_user_id,
    exists (
      select 1
      from public.blackcrown_entitlements e
      where e.account_id = a.id
        and e.entitlement_key = 'blackcrown.premium'
        and e.status = 'active'
        and e.starts_at <= now()
        and (e.expires_at is null or e.expires_at > now())
    ) as premium_active,
    coalesce((
      select array_agg(e.entitlement_key order by e.entitlement_key)
      from public.blackcrown_entitlements e
      where e.account_id = a.id
        and e.status = 'active'
        and e.starts_at <= now()
        and (e.expires_at is null or e.expires_at > now())
    ), array[]::text[]) as entitlement_keys
  from public.blackcrown_telegram_links l
  join public.blackcrown_accounts a on a.id = l.account_id
  where l.telegram_user_id = p_telegram_user_id;
$$;

create or replace function public.blackcrown_unlink_site_telegram(
  p_site_user_id text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_account_id uuid;
  v_deleted integer;
begin
  select id into v_account_id
  from public.blackcrown_accounts
  where site_user_id = p_site_user_id;

  if not found then
    return false;
  end if;

  delete from public.blackcrown_telegram_links
  where account_id = v_account_id;
  get diagnostics v_deleted = row_count;

  if v_deleted > 0 then
    insert into public.blackcrown_account_events(
      account_id,
      event_type,
      actor
    ) values (
      v_account_id,
      'telegram.unlinked',
      'site'
    );
  end if;

  return v_deleted > 0;
end;
$$;

create or replace function public.blackcrown_unlink_telegram_user(
  p_telegram_user_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_account_id uuid;
  v_deleted integer;
begin
  select account_id into v_account_id
  from public.blackcrown_telegram_links
  where telegram_user_id = p_telegram_user_id;

  if not found then
    return false;
  end if;

  delete from public.blackcrown_telegram_links
  where telegram_user_id = p_telegram_user_id;
  get diagnostics v_deleted = row_count;

  if v_deleted > 0 then
    insert into public.blackcrown_account_events(
      account_id,
      event_type,
      actor
    ) values (
      v_account_id,
      'telegram.unlinked',
      'telegram'
    );
  end if;

  return v_deleted > 0;
end;
$$;

create or replace function public.blackcrown_grant_entitlement(
  p_site_user_id text,
  p_entitlement_key text,
  p_source text default 'admin',
  p_expires_at timestamptz default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_account_id uuid;
begin
  if p_site_user_id is null
     or p_site_user_id !~ '^[A-Za-z0-9_.:@-]{1,160}$' then
    raise exception using errcode = 'P0001', message = 'invalid_site_user_id';
  end if;
  if p_entitlement_key is null
     or p_entitlement_key !~ '^[a-z0-9._-]{1,80}$' then
    raise exception using errcode = 'P0001', message = 'invalid_entitlement_key';
  end if;
  if p_source not in ('payment', 'admin', 'promo', 'migration', 'system') then
    raise exception using errcode = 'P0001', message = 'invalid_entitlement_source';
  end if;
  if p_expires_at is not null and p_expires_at <= now() then
    raise exception using errcode = 'P0001', message = 'invalid_entitlement_expiry';
  end if;
  if p_metadata is null or jsonb_typeof(p_metadata) <> 'object' then
    raise exception using errcode = 'P0001', message = 'invalid_entitlement_metadata';
  end if;

  insert into public.blackcrown_accounts(site_user_id)
  values (p_site_user_id)
  on conflict (site_user_id) do update set updated_at = now()
  returning id into v_account_id;

  insert into public.blackcrown_entitlements(
    account_id,
    entitlement_key,
    status,
    source,
    starts_at,
    expires_at,
    metadata
  ) values (
    v_account_id,
    p_entitlement_key,
    'active',
    p_source,
    now(),
    p_expires_at,
    p_metadata
  )
  on conflict (account_id, entitlement_key) do update set
    status = 'active',
    source = excluded.source,
    starts_at = now(),
    expires_at = excluded.expires_at,
    metadata = excluded.metadata,
    updated_at = now();

  insert into public.blackcrown_account_events(
    account_id,
    event_type,
    actor,
    metadata
  ) values (
    v_account_id,
    'entitlement.granted',
    p_source,
    jsonb_build_object(
      'entitlement_key', p_entitlement_key,
      'expires_at', p_expires_at
    )
  );
end;
$$;

create or replace function public.blackcrown_revoke_entitlement(
  p_site_user_id text,
  p_entitlement_key text,
  p_actor text default 'admin'
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_account_id uuid;
  v_updated integer;
begin
  select id into v_account_id
  from public.blackcrown_accounts
  where site_user_id = p_site_user_id;

  if not found then
    return false;
  end if;

  update public.blackcrown_entitlements
  set status = 'revoked', updated_at = now()
  where account_id = v_account_id
    and entitlement_key = p_entitlement_key
    and status <> 'revoked';
  get diagnostics v_updated = row_count;

  if v_updated > 0 then
    insert into public.blackcrown_account_events(
      account_id,
      event_type,
      actor,
      metadata
    ) values (
      v_account_id,
      'entitlement.revoked',
      left(regexp_replace(lower(coalesce(p_actor, 'admin')), '[^a-z0-9._-]', '', 'g'), 40),
      jsonb_build_object('entitlement_key', p_entitlement_key)
    );
  end if;

  return v_updated > 0;
end;
$$;

revoke all on function public.blackcrown_bridge_touch_updated_at()
  from public, anon, authenticated;
revoke all on function public.blackcrown_issue_telegram_link_code(text, text, timestamptz)
  from public, anon, authenticated;
revoke all on function public.blackcrown_consume_telegram_link_code(text, bigint, bigint, text)
  from public, anon, authenticated;
revoke all on function public.blackcrown_get_site_telegram_status(text)
  from public, anon, authenticated;
revoke all on function public.blackcrown_get_telegram_identity(bigint)
  from public, anon, authenticated;
revoke all on function public.blackcrown_unlink_site_telegram(text)
  from public, anon, authenticated;
revoke all on function public.blackcrown_unlink_telegram_user(bigint)
  from public, anon, authenticated;
revoke all on function public.blackcrown_grant_entitlement(text, text, text, timestamptz, jsonb)
  from public, anon, authenticated;
revoke all on function public.blackcrown_revoke_entitlement(text, text, text)
  from public, anon, authenticated;

grant execute on function public.blackcrown_issue_telegram_link_code(text, text, timestamptz)
  to service_role;
grant execute on function public.blackcrown_consume_telegram_link_code(text, bigint, bigint, text)
  to service_role;
grant execute on function public.blackcrown_get_site_telegram_status(text)
  to service_role;
grant execute on function public.blackcrown_get_telegram_identity(bigint)
  to service_role;
grant execute on function public.blackcrown_unlink_site_telegram(text)
  to service_role;
grant execute on function public.blackcrown_unlink_telegram_user(bigint)
  to service_role;
grant execute on function public.blackcrown_grant_entitlement(text, text, text, timestamptz, jsonb)
  to service_role;
grant execute on function public.blackcrown_revoke_entitlement(text, text, text)
  to service_role;

-- The public status trigger is internal-only as well. Its table remains
-- browser-readable through its dedicated SELECT policy.
do $$
begin
  if to_regprocedure('public.blackcrown_set_updated_at()') is not null then
    execute 'revoke all on function public.blackcrown_set_updated_at() from public, anon, authenticated';
  end if;
end;
$$;
