create extension if not exists pgcrypto with schema extensions;

create table if not exists public.blackcrown_telegram_link_challenges (
  id uuid primary key default extensions.gen_random_uuid(),
  code_hash text not null unique check (code_hash ~ '^[0-9a-f]{64}$'),
  telegram_user_id bigint not null check (telegram_user_id > 0),
  telegram_chat_id bigint not null,
  telegram_username text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  check (expires_at > created_at)
);

create index if not exists blackcrown_link_challenges_telegram_idx
  on public.blackcrown_telegram_link_challenges (telegram_user_id, created_at desc);

create index if not exists blackcrown_link_challenges_expiry_idx
  on public.blackcrown_telegram_link_challenges (expires_at)
  where consumed_at is null;

create table if not exists public.blackcrown_account_links (
  site_user_id text primary key
    check (length(site_user_id) between 1 and 160)
    check (site_user_id ~ '^[A-Za-z0-9_.:@-]+$'),
  telegram_user_id bigint not null unique check (telegram_user_id > 0),
  telegram_chat_id bigint not null,
  telegram_username text,
  status text not null default 'active' check (status in ('active', 'revoked')),
  linked_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.blackcrown_entitlements (
  id uuid primary key default extensions.gen_random_uuid(),
  site_user_id text not null
    check (length(site_user_id) between 1 and 160)
    check (site_user_id ~ '^[A-Za-z0-9_.:@-]+$'),
  entitlement_key text not null
    check (length(entitlement_key) between 1 and 80)
    check (entitlement_key ~ '^[a-z0-9_.:-]+$'),
  status text not null default 'active' check (status in ('active', 'revoked', 'expired')),
  source text not null default 'manual' check (length(source) between 1 and 64),
  valid_from timestamptz not null default now(),
  valid_until timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (valid_until is null or valid_until > valid_from),
  unique (site_user_id, entitlement_key, source)
);

create index if not exists blackcrown_entitlements_active_idx
  on public.blackcrown_entitlements (site_user_id, entitlement_key, valid_until)
  where status = 'active';

create table if not exists public.blackcrown_account_link_events (
  id bigint generated by default as identity primary key,
  site_user_id text,
  telegram_user_id bigint,
  event_type text not null check (event_type in ('linked', 'link_refreshed', 'unlinked_by_telegram')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists blackcrown_account_link_events_site_idx
  on public.blackcrown_account_link_events (site_user_id, id desc);

create index if not exists blackcrown_account_link_events_telegram_idx
  on public.blackcrown_account_link_events (telegram_user_id, id desc);

alter table public.blackcrown_telegram_link_challenges enable row level security;
alter table public.blackcrown_account_links enable row level security;
alter table public.blackcrown_entitlements enable row level security;
alter table public.blackcrown_account_link_events enable row level security;

revoke all on table public.blackcrown_telegram_link_challenges from public, anon, authenticated;
revoke all on table public.blackcrown_account_links from public, anon, authenticated;
revoke all on table public.blackcrown_entitlements from public, anon, authenticated;
revoke all on table public.blackcrown_account_link_events from public, anon, authenticated;

revoke all on sequence public.blackcrown_account_link_events_id_seq from public, anon, authenticated;

grant select, insert, update, delete on table public.blackcrown_telegram_link_challenges to service_role;
grant select, insert, update, delete on table public.blackcrown_account_links to service_role;
grant select, insert, update, delete on table public.blackcrown_entitlements to service_role;
grant select, insert, update, delete on table public.blackcrown_account_link_events to service_role;
grant usage, select on sequence public.blackcrown_account_link_events_id_seq to service_role;

create or replace function public.blackcrown_create_telegram_link_challenge(
  p_code_hash text,
  p_telegram_user_id bigint,
  p_telegram_chat_id bigint,
  p_telegram_username text default null,
  p_ttl_seconds integer default 600
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_ttl integer;
  v_expires_at timestamptz;
  v_username text;
begin
  if p_code_hash is null or p_code_hash !~ '^[0-9a-f]{64}$' then
    return jsonb_build_object('ok', false, 'reason', 'invalid_code_hash');
  end if;
  if p_telegram_user_id is null or p_telegram_user_id <= 0 or p_telegram_chat_id is null then
    return jsonb_build_object('ok', false, 'reason', 'invalid_telegram_identity');
  end if;

  v_ttl := greatest(60, least(coalesce(p_ttl_seconds, 600), 900));
  v_expires_at := now() + make_interval(secs => v_ttl);
  v_username := nullif(left(regexp_replace(coalesce(p_telegram_username, ''), '[^A-Za-z0-9_]', '', 'g'), 64), '');

  update public.blackcrown_telegram_link_challenges
     set consumed_at = now()
   where telegram_user_id = p_telegram_user_id
     and consumed_at is null;

  delete from public.blackcrown_telegram_link_challenges
   where expires_at < now() - interval '1 day';

  insert into public.blackcrown_telegram_link_challenges (
    code_hash,
    telegram_user_id,
    telegram_chat_id,
    telegram_username,
    expires_at
  ) values (
    p_code_hash,
    p_telegram_user_id,
    p_telegram_chat_id,
    v_username,
    v_expires_at
  );

  return jsonb_build_object(
    'ok', true,
    'expires_at', v_expires_at,
    'ttl_seconds', v_ttl
  );
end;
$$;

create or replace function public.blackcrown_complete_telegram_link(
  p_code text,
  p_site_user_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_hash text;
  v_challenge public.blackcrown_telegram_link_challenges%rowtype;
  v_existing_site public.blackcrown_account_links%rowtype;
  v_existing_telegram public.blackcrown_account_links%rowtype;
  v_entitlements text[] := array[]::text[];
  v_premium boolean := false;
  v_event text := 'linked';
begin
  if p_code is null or length(p_code) < 32 or length(p_code) > 128 or p_code !~ '^[A-Za-z0-9_-]+$' then
    return jsonb_build_object('ok', false, 'reason', 'invalid_or_expired_code');
  end if;
  if p_site_user_id is null
     or length(p_site_user_id) < 1
     or length(p_site_user_id) > 160
     or p_site_user_id !~ '^[A-Za-z0-9_.:@-]+$' then
    return jsonb_build_object('ok', false, 'reason', 'invalid_site_user');
  end if;

  v_hash := encode(extensions.digest(convert_to(p_code, 'UTF8'), 'sha256'), 'hex');

  select *
    into v_challenge
    from public.blackcrown_telegram_link_challenges
   where code_hash = v_hash
     and consumed_at is null
     and expires_at > now()
   for update;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'invalid_or_expired_code');
  end if;

  select * into v_existing_site
    from public.blackcrown_account_links
   where site_user_id = p_site_user_id
     and status = 'active';

  if found and v_existing_site.telegram_user_id <> v_challenge.telegram_user_id then
    return jsonb_build_object('ok', false, 'reason', 'site_already_linked');
  end if;

  select * into v_existing_telegram
    from public.blackcrown_account_links
   where telegram_user_id = v_challenge.telegram_user_id
     and status = 'active';

  if found and v_existing_telegram.site_user_id <> p_site_user_id then
    return jsonb_build_object('ok', false, 'reason', 'telegram_already_linked');
  end if;

  if v_existing_site.site_user_id is not null then
    v_event := 'link_refreshed';
    update public.blackcrown_account_links
       set telegram_chat_id = v_challenge.telegram_chat_id,
           telegram_username = v_challenge.telegram_username,
           updated_at = now()
     where site_user_id = p_site_user_id;
  else
    insert into public.blackcrown_account_links (
      site_user_id,
      telegram_user_id,
      telegram_chat_id,
      telegram_username,
      status
    ) values (
      p_site_user_id,
      v_challenge.telegram_user_id,
      v_challenge.telegram_chat_id,
      v_challenge.telegram_username,
      'active'
    );
  end if;

  update public.blackcrown_telegram_link_challenges
     set consumed_at = now()
   where id = v_challenge.id;

  insert into public.blackcrown_account_link_events (
    site_user_id,
    telegram_user_id,
    event_type,
    metadata
  ) values (
    p_site_user_id,
    v_challenge.telegram_user_id,
    v_event,
    jsonb_build_object('challenge_id', v_challenge.id)
  );

  select coalesce(array_agg(entitlement_key order by entitlement_key), array[]::text[])
    into v_entitlements
    from public.blackcrown_entitlements
   where site_user_id = p_site_user_id
     and status = 'active'
     and valid_from <= now()
     and (valid_until is null or valid_until > now());

  v_premium := 'bco_premium' = any(v_entitlements);

  return jsonb_build_object(
    'ok', true,
    'linked', true,
    'premium', v_premium,
    'entitlements', to_jsonb(v_entitlements),
    'linked_at', now()
  );
exception
  when unique_violation then
    return jsonb_build_object('ok', false, 'reason', 'link_conflict');
end;
$$;

create or replace function public.blackcrown_get_site_telegram_status(
  p_site_user_id text
)
returns jsonb
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_link public.blackcrown_account_links%rowtype;
  v_entitlements text[] := array[]::text[];
  v_premium boolean := false;
begin
  if p_site_user_id is null
     or length(p_site_user_id) < 1
     or length(p_site_user_id) > 160
     or p_site_user_id !~ '^[A-Za-z0-9_.:@-]+$' then
    return jsonb_build_object('ok', false, 'reason', 'invalid_site_user');
  end if;

  select * into v_link
    from public.blackcrown_account_links
   where site_user_id = p_site_user_id
     and status = 'active';

  if not found then
    return jsonb_build_object(
      'ok', true,
      'linked', false,
      'premium', false,
      'entitlements', '[]'::jsonb
    );
  end if;

  select coalesce(array_agg(entitlement_key order by entitlement_key), array[]::text[])
    into v_entitlements
    from public.blackcrown_entitlements
   where site_user_id = p_site_user_id
     and status = 'active'
     and valid_from <= now()
     and (valid_until is null or valid_until > now());

  v_premium := 'bco_premium' = any(v_entitlements);

  return jsonb_build_object(
    'ok', true,
    'linked', true,
    'premium', v_premium,
    'entitlements', to_jsonb(v_entitlements),
    'linked_at', v_link.linked_at
  );
end;
$$;

create or replace function public.blackcrown_get_telegram_entitlement_status(
  p_telegram_user_id bigint
)
returns jsonb
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_link public.blackcrown_account_links%rowtype;
  v_entitlements text[] := array[]::text[];
  v_premium boolean := false;
begin
  if p_telegram_user_id is null or p_telegram_user_id <= 0 then
    return jsonb_build_object('ok', false, 'reason', 'invalid_telegram_identity');
  end if;

  select * into v_link
    from public.blackcrown_account_links
   where telegram_user_id = p_telegram_user_id
     and status = 'active';

  if not found then
    return jsonb_build_object(
      'ok', true,
      'linked', false,
      'premium', false,
      'entitlements', '[]'::jsonb
    );
  end if;

  select coalesce(array_agg(entitlement_key order by entitlement_key), array[]::text[])
    into v_entitlements
    from public.blackcrown_entitlements
   where site_user_id = v_link.site_user_id
     and status = 'active'
     and valid_from <= now()
     and (valid_until is null or valid_until > now());

  v_premium := 'bco_premium' = any(v_entitlements);

  return jsonb_build_object(
    'ok', true,
    'linked', true,
    'site_user_id', v_link.site_user_id,
    'premium', v_premium,
    'entitlements', to_jsonb(v_entitlements),
    'linked_at', v_link.linked_at
  );
end;
$$;

create or replace function public.blackcrown_unlink_telegram(
  p_telegram_user_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_link public.blackcrown_account_links%rowtype;
begin
  if p_telegram_user_id is null or p_telegram_user_id <= 0 then
    return jsonb_build_object('ok', false, 'reason', 'invalid_telegram_identity');
  end if;

  delete from public.blackcrown_account_links
   where telegram_user_id = p_telegram_user_id
   returning * into v_link;

  if not found then
    return jsonb_build_object('ok', true, 'unlinked', false);
  end if;

  insert into public.blackcrown_account_link_events (
    site_user_id,
    telegram_user_id,
    event_type
  ) values (
    v_link.site_user_id,
    v_link.telegram_user_id,
    'unlinked_by_telegram'
  );

  return jsonb_build_object('ok', true, 'unlinked', true);
end;
$$;

revoke all on function public.blackcrown_create_telegram_link_challenge(text, bigint, bigint, text, integer)
  from public, anon, authenticated;
revoke all on function public.blackcrown_complete_telegram_link(text, text)
  from public, anon, authenticated;
revoke all on function public.blackcrown_get_site_telegram_status(text)
  from public, anon, authenticated;
revoke all on function public.blackcrown_get_telegram_entitlement_status(bigint)
  from public, anon, authenticated;
revoke all on function public.blackcrown_unlink_telegram(bigint)
  from public, anon, authenticated;

grant execute on function public.blackcrown_create_telegram_link_challenge(text, bigint, bigint, text, integer)
  to service_role;
grant execute on function public.blackcrown_get_telegram_entitlement_status(bigint)
  to service_role;
grant execute on function public.blackcrown_unlink_telegram(bigint)
  to service_role;

grant execute on function public.blackcrown_complete_telegram_link(text, text)
  to anon, authenticated;
grant execute on function public.blackcrown_get_site_telegram_status(text)
  to anon, authenticated;

comment on table public.blackcrown_account_links is
  'Server-owned mapping between a BlackCrown site account and one Telegram identity.';
comment on table public.blackcrown_entitlements is
  'Authoritative server-only product entitlements. Account linking never grants entitlement rows.';
comment on function public.blackcrown_complete_telegram_link(text, text) is
  'Consumes a high-entropy one-time bearer token and links it to the signed site account supplied by the Pages backend.';
