import * as THREE from "three";
import type { MoveVector } from "../input/InputController";
import type { PlayerZone } from "../../simulation/model";

export type InteractableId="locker"|"workshop-bin"|"service-hatch";
export type SceneFrame={playerZone:PlayerZone;guardCanSeePlayer:boolean;nearestInteractable:InteractableId|null;guardDistance:number};
type Collider={minX:number;maxX:number;minZ:number;maxZ:number;enabled:boolean};
type Interactable={id:InteractableId;position:THREE.Vector3;marker:THREE.Mesh};
const PLAYER_RADIUS=.42,PLAYER_SPEED=4.2;
const mat=(color:number,roughness=.9,metalness=.02)=>new THREE.MeshStandardMaterial({color,roughness,metalness});
function character(bodyColor:number,trimColor:number){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.72,4,8),mat(bodyColor,.8));body.position.y=1.05;body.castShadow=true;const head=new THREE.Mesh(new THREE.SphereGeometry(.28,12,10),mat(0xcaa985,.92));head.position.y=1.82;head.castShadow=true;const trim=new THREE.Mesh(new THREE.BoxGeometry(.76,.15,.4),mat(trimColor,.72));trim.position.set(0,1.18,-.16);trim.castShadow=true;g.add(body,head,trim);return g;}
export class PrisonScene{
readonly renderer:THREE.WebGLRenderer;readonly scene=new THREE.Scene();readonly camera:THREE.OrthographicCamera;readonly player=character(0xc56432,0x2a1710);readonly guard=character(0x243947,0x8eb7c8);
private readonly container:HTMLElement;private readonly colliders:Collider[]=[];private readonly interactables:Interactable[]=[];private readonly clock=new THREE.Clock();private readonly guardPatrol=[new THREE.Vector3(-.5,0,6.7),new THREE.Vector3(5.7,0,6.7),new THREE.Vector3(5.7,0,1.4),new THREE.Vector3(.4,0,1.4),new THREE.Vector3(.4,0,-2.7)];private readonly prisoners:THREE.Group[]=[];private guardIndex=0;private hatchCollider:Collider|null=null;private disposed=false;
constructor(container:HTMLElement){this.container=container;this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:"high-performance"});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.renderer.domElement.className="breakoutCanvas";container.appendChild(this.renderer.domElement);this.scene.background=new THREE.Color(0x10171b);this.scene.fog=new THREE.FogExp2(0x10171b,.027);this.camera=new THREE.OrthographicCamera(-9,9,6,-6,.1,80);this.camera.position.set(11,14,14);this.camera.lookAt(0,0,2);this.buildLighting();this.buildPrison();this.buildActors();this.resize();window.addEventListener("resize",this.resize);}
private buildLighting(){this.scene.add(new THREE.HemisphereLight(0x9cb7c9,0x161a1d,2.2));const sun=new THREE.DirectionalLight(0xf2e0c4,4.6);sun.position.set(-7,15,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-18;sun.shadow.camera.right=18;sun.shadow.camera.top=18;sun.shadow.camera.bottom=-18;sun.shadow.bias=-.0002;this.scene.add(sun);const light=new THREE.PointLight(0xa9d4e6,24,11,2.2);light.position.set(2.8,4.2,4.5);this.scene.add(light);}
private floor(x:number,z:number,w:number,d:number,color:number){const m=new THREE.Mesh(new THREE.BoxGeometry(w,.22,d),mat(color,.98));m.position.set(x,-.11,z);m.receiveShadow=true;this.scene.add(m);}
private wall(x:number,z:number,w:number,d:number,h=2.8,collider=true){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(0x586168,.94));mesh.position.set(x,h/2,z);mesh.castShadow=true;mesh.receiveShadow=true;this.scene.add(mesh);if(!collider)return null;const c={minX:x-w/2,maxX:x+w/2,minZ:z-d/2,maxZ:z+d/2,enabled:true};this.colliders.push(c);return c;}
private prop(x:number,z:number,w:number,d:number,h:number,color:number){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color,.86));mesh.position.set(x,h/2,z);mesh.castShadow=true;mesh.receiveShadow=true;this.scene.add(mesh);return mesh;}
private interactable(id:InteractableId,x:number,z:number,color:number){const ring=new THREE.Mesh(new THREE.RingGeometry(.52,.65,28),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.58,side:THREE.DoubleSide,depthWrite:false}));ring.position.set(x,.04,z);ring.rotation.x=-Math.PI/2;this.scene.add(ring);this.interactables.push({id,position:new THREE.Vector3(x,0,z),marker:ring});}
private label(text:string,x:number,z:number,color:number){const c=document.createElement("canvas");c.width=512;c.height=128;const ctx=c.getContext("2d");if(!ctx)return;ctx.font="700 42px system-ui";ctx.textAlign="center";ctx.fillStyle="rgba(255,255,255,.88)";ctx.fillText(text,256,76);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,color,transparent:true,depthWrite:false}));sprite.position.set(x,.04,z);sprite.scale.set(3.8,.95,1);sprite.rotation.x=-Math.PI/2;this.scene.add(sprite);}
private buildPrison(){this.floor(1.5,2.5,23,17,0x252c30);this.floor(-5.5,6.1,5.3,4.8,0x30383d);this.floor(-5.5,-2.4,5.3,4.3,0x363536);this.floor(-5.4,2.1,5.4,3.4,0x2d3336);this.floor(3.2,-2.7,7.8,4.2,0x313a38);this.floor(10,4.4,4,6.4,0x1f292a);
this.wall(1.5,10.9,23.4,.35,3.2);this.wall(1.5,-6,23.4,.35,3.2);this.wall(-10.2,2.45,.35,17.25,3.2);this.wall(13.2,2.45,.35,17.25,3.2);this.wall(-8.2,3.7,.25,5);this.wall(-5.5,8.5,5.65,.25);this.wall(-2.8,6.9,.25,3.25);this.wall(-2.8,4.05,.25,1.25);this.wall(-5.5,3.7,5.65,.25);this.wall(-5.5,.35,5.65,.25);this.wall(-5.5,-4.65,5.65,.25);this.wall(-2.8,-2.4,.25,4.75);this.wall(-8.2,-2.4,.25,4.75);this.wall(-5.5,3.85,5.65,.25);this.wall(8.05,8,.25,5.7);this.wall(8.05,.55,.25,4.1);this.hatchCollider=this.wall(8.05,4.75,.25,1.45,2.4);
this.prop(-6.65,6.65,2.15,.9,.45,0x747d82);this.prop(-4,7.35,.9,.55,1.9,0x485057);this.prop(-5.1,4.45,1.2,.7,.78,0x50595e);this.interactable("locker",-4,7.35,0xe4a95e);this.prop(-5.6,2.15,3.6,.9,.8,0x4c5558);this.prop(-7.3,1.15,.9,.9,.8,0x6b5a43);this.interactable("workshop-bin",-7.3,1.15,0xf0cc77);for(const x of[-6.6,-4.2])this.prop(x,-2.4,1.45,.7,.72,0x5c554b);for(let i=0;i<4;i++){const line=new THREE.Mesh(new THREE.BoxGeometry(.08,.03,2.6),mat(0xb8c6bd));line.position.set(.9+i*1.5,.025,-2.8);this.scene.add(line);}this.prop(10.55,6.45,2,1.1,1.55,0x394647);this.prop(11,2.15,1.1,1.1,2,0x334244);this.interactable("service-hatch",7.55,4.75,0x65d4d8);this.label("CELL",-5.5,5.2,0xa8c0c7);this.label("WORK",-5.4,2.8,0xa8c0c7);this.label("CANTEEN",-5.5,-1,0xb5ae9b);this.label("ROLL CALL",3.2,-4.2,0x9db7ad);this.label("MAINTENANCE",10,7.1,0x6fbfc1);for(let i=-1;i<=3;i++){const f=new THREE.Mesh(new THREE.BoxGeometry(.18,.06,2),new THREE.MeshStandardMaterial({color:0xb8dbe2,emissive:0x78aeba,emissiveIntensity:2.2}));f.position.set(i*2.2+1.2,2.85,6.7);this.scene.add(f);}}
private buildActors(){this.player.position.set(-5.45,0,5.25);this.player.rotation.y=Math.PI;this.scene.add(this.player);this.guard.position.copy(this.guardPatrol[0]);this.scene.add(this.guard);[new THREE.Vector3(2,0,-2.4),new THREE.Vector3(3.7,0,-3),new THREE.Vector3(5.2,0,-2.2)].forEach((p,i)=>{const n=character(0xb95f33+i*0x080300,0x2f1c14);n.position.copy(p);n.scale.setScalar(.93+i*.025);this.prisoners.push(n);this.scene.add(n);});}
private blocked(x:number,z:number){return this.colliders.some(c=>c.enabled&&x+PLAYER_RADIUS>c.minX&&x-PLAYER_RADIUS<c.maxX&&z+PLAYER_RADIUS>c.minZ&&z-PLAYER_RADIUS<c.maxZ);}
private move(move:MoveVector,dt:number){const dx=move.x*PLAYER_SPEED*dt,dz=move.z*PLAYER_SPEED*dt;if(Math.abs(dx)+Math.abs(dz)<.0001){this.player.position.y=0;return;}const nx=THREE.MathUtils.clamp(this.player.position.x+dx,-9.45,12.45);if(!this.blocked(nx,this.player.position.z))this.player.position.x=nx;const nz=THREE.MathUtils.clamp(this.player.position.z+dz,-5.25,10.15);if(!this.blocked(this.player.position.x,nz))this.player.position.z=nz;this.player.rotation.y=Math.atan2(move.x,move.z);this.player.position.y=Math.sin(performance.now()*.014)*.035;}
private updateGuard(dt:number){const t=this.guardPatrol[this.guardIndex],d=t.clone().sub(this.guard.position);d.y=0;if(d.lengthSq()<.12){this.guardIndex=(this.guardIndex+1)%this.guardPatrol.length;return;}d.normalize();this.guard.position.addScaledVector(d,dt*1.75);this.guard.rotation.y=Math.atan2(d.x,d.z);}
private watch(){const v=this.player.position.clone().sub(this.guard.position);v.y=0;const distance=v.length();if(distance>6.4)return{visible:false,distance};const forward=new THREE.Vector3(Math.sin(this.guard.rotation.y),0,Math.cos(this.guard.rotation.y));return{visible:forward.dot(v.normalize())>.12,distance};}
getPlayerZone():PlayerZone{const{x,z}=this.player.position;if(x>8.1)return"maintenance";if(x<-2.8&&z>3.7)return"cell";if(x<-2.8&&z<.35)return"canteen";if(x<-2.8&&z>=.35&&z<=3.85)return"workshop";if(x>=-.5&&x<=7.2&&z<0)return"roll-call";return"corridor";}
private nearest(){let best:{id:InteractableId;distance:number}|null=null;for(const i of this.interactables){const d=i.position.distanceTo(this.player.position);const m=i.marker.material as THREE.MeshBasicMaterial;m.opacity=d<1.65?.95:.48;i.marker.scale.setScalar(d<1.65?1.15:1);if(d<=1.65&&(!best||d<best.distance))best={id:i.id,distance:d};}return best?.id??null;}
setServiceHatchUnlocked(unlocked:boolean){if(this.hatchCollider)this.hatchCollider.enabled=!unlocked;const marker=this.interactables.find(i=>i.id==="service-hatch")?.marker;if(marker)(marker.material as THREE.MeshBasicMaterial).color.set(unlocked?0x6ddf93:0x65d4d8);}
resetPlayerToCell(){this.player.position.set(-5.45,0,5.25);}
update(move:MoveVector):SceneFrame{const dt=Math.min(this.clock.getDelta(),.05),elapsed=this.clock.elapsedTime;this.move(move,dt);this.updateGuard(dt);this.prisoners.forEach((p,i)=>{p.rotation.y=Math.sin(elapsed*.2+i)*.7;});const seen=this.watch(),target=this.player.position.clone().lerp(new THREE.Vector3(1.5,0,2.6),.45),offset=new THREE.Vector3(11,14,14);this.camera.position.copy(target).add(offset);this.camera.lookAt(target.x,.2,target.z);this.renderer.render(this.scene,this.camera);return{playerZone:this.getPlayerZone(),guardCanSeePlayer:seen.visible,nearestInteractable:this.nearest(),guardDistance:seen.distance};}
private resize=()=>{if(this.disposed)return;const w=Math.max(1,this.container.clientWidth),h=Math.max(1,this.container.clientHeight),aspect=w/h,v=7.4;this.camera.left=-v*aspect;this.camera.right=v*aspect;this.camera.top=v;this.camera.bottom=-v;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);};
dispose(){this.disposed=true;window.removeEventListener("resize",this.resize);this.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}});this.renderer.dispose();this.renderer.domElement.remove();}}
